### ISSUE TITLE
Import form pip install vs local install

### ISSUE THREAD

**Issue by shihfangchen** [facebookresearch/pytorch3d#102]
Hi, I wanna ask how to import pytorch3d after the local install.

When I install by
```
!git clone https://github.com/facebookresearch/pytorch3d.git
!cd pytorch3d && pip install -e .
```
and using this quoto

> from pytorch3d.io import load_obj, save_obj

it returns 

> ModuleNotFoundError: No module named 'pytorch3d.io' 

then I change it to 
![image](https://user-images.githubusercontent.com/14999043/75956924-e3cabd00-5ef3-11ea-868e-054516430b7d.png)

it returns
![image](https://user-images.githubusercontent.com/14999043/75957124-4de36200-5ef4-11ea-9702-5655bfe69cfd.png)

how to redirect all pytorch3d path to correct pah or
are there any way to solve it

**Comment by bottler** [comment]
Could it be that the command `!cd pytorch3d && pip install -e .` failed? What was its output? I think you haven't successfully built/installed pytorch3d, and it can just see the files in the working directory. This means that (whether or not there are path issues) you won't have access to the compiled parts of pytorch3d.

**Comment by nikhilaravi** [comment]
@shihfangchen did you check the installation was completed correctly? If you don't need help anymore please close this issue.

**Comment by jmagoon** [comment]
Hi, I wanted to mention that I had this error and realized it was because I named my script `pytorch3d.py` -- so even though everything was installed properly python was trying to resolve `pytorch3d.io` based on the filename of the script itself. 😬 

In the case above it looks like the folder name of the project is `pytorch3d/`, so the script is trying to resolve from there (e.g. why pytorch3d.pytorch3d works) and then hitting various name collisions, since `pytorch3d` will still refer to the base folder.

Just in case that helps anyone in the future.
