### ISSUE TITLE
installed conda package does not have HarmonicEmbedding class

### ISSUE THREAD

**Issue by orweiser-code** [facebookresearch/pytorch3d#1050]
Hi,
Installed on a clean environment pytorch3d version 0.6.1 following steps in readme.
trying to test out the nerf project but fail due to missing import for

`from pytroch3d.renderer import HarmonicEmbedding`

looking at the source files under site-packages in the relevant environment - I see that indeed the `pytorch3d/renderer/__init__.py` is missing this import.
in fact, the module itself is missing as though it installed an earlier version of this module (obviously when I print out `print(pytorch3d.__version__)` I get the correct output - 0.6.1).

can you please assist?

**Comment by bottler** [comment]
The move of HarmonicEmbedding from the NeRF project code to `pytorch3d.renderer` happened since the latest release 0.6.1 of PyTorch3D. It is visible on the `main` branch. If you have installed version 0.6.1 and have a git clone of this repo for working with NeRF, I suggest you checkout the `v0.6.1` tag and use the NeRF project from there.

**Comment by orweiser-code** [comment]
I see that now... thank you!
