### ISSUE TITLE
Subpixel accuracy different by projection in release 0.6.1 and 0.5

### ISSUE THREAD

**Issue by YuxuanSnow** [facebookresearch/pytorch3d#1156]
Dear Developers,

i recently upgrade from release 0.5 to 0.6.1.

I tried to project barycentric interpolated face location of a mesh. I use `renderer.cameras.transform_points_screen(pixel_vals)`. In release 0.5, the projected 2D location of 3D face has subpixel accuracy, while in the release 0.6.1 all 2D projection has `ux+0.5, uy+0.5` (ux and uy is the pixel location of that face from `pixel_to_face`). It seems the projection of 3D points corresponds to a pixel, but the subpixel accuracy misses. 

I wonder if you use now the nearest neighbor in projection? If not, how can i have the subpixel accuracy again?

Thank you!

**Comment by bottler** [comment]
Assuming your camera has in_ndc=True.

The behaviour of transform_points_screen was changed in v0.6.1 from "align_corners=True" to "align_corners=False", so that it now matches the way the camera is used elsewhere - e.g. inside the renderers. It should be easier now to match what would be expected. In particular, a point which is in the center of a pixel will have the corresponding output of transform_points_screen halfway between integers, as NDC space goes from the edge of the outer pixels. The file `test_camera_pixels.py` gives a detailed illustration.

**Comment by YuxuanSnow** [comment]
Appreciate a lot!
