### ISSUE TITLE
pulsar: Return alpha channel

### ISSUE THREAD

**Issue by neverix** [facebookresearch/pytorch3d#1219]
## 🚀 Feature
Include the alpha transparency as the 14th channel in `forw_info` in Pulsar.

## Motivation

It's currently impossible to properly render images on top of a background without hacks. Returning the real alpha would broaden the scope of applications for Pulsar.

## Pitch
Unfortunately, I've only barely skimmed the C++ backend code. The frontend code would look like this;

```
_, forw_info = renderer(...)  # forw_info :: torch.Size([X, Y, 14]) (not 13)
forw_info[..., -1]  # alpha channel, 0-1
```

**Comment by classner** [comment]
Hi @neverix !

What kind of information are you looking for, i.e., what exactly should alpha contain?

**Comment by neverix** [comment]
A black/white map of whether a pixel belongs to the white background. It should ideally be differentiable too.

I've since solved the issue by setting all sphere colors to black and rendering again. So if this feature is ever implemented, it can be done in the Python wrapper at the cost of a 2x slowdown.

**Comment by classner** [comment]
Hi @neverix !

The `forw_info` tensor is not differentiable by design - it stores exactly the information that is needed for differentiation later. So this wouldn’t be a good place to store this differentiable. If you do want differentiability, the route you went is the best you can do.

I wouldn’t add this as a standalone feature to the renderer because it seems quite application specific (and not hard to do if required).
