### ISSUE TITLE
Install fails on Linux following install.md

### ISSUE THREAD

**Issue by yichao-liang** [facebookresearch/pytorch3d#1225]
Hi, 

I'm trying to install pytorch3d following stringently [INSTALL.md](https://github.com/facebookresearch/pytorch3d/blob/main/INSTALL.md), on a CentOS Linux 7 (Core) server but have been unsuccessful when I proceed to run
`conda install pytorch3d -c pytorch3d`, which leads to conflict in the environment (with more error output attached below).
I've tried to create new environments and install again several times, but all result in the same state. 

Could you please help me troubleshoot this? Is this just on my machine, or also happening to others?

The detailed system output:
[install_log.txt](https://github.com/facebookresearch/pytorch3d/files/8898344/install_log.txt)

**Comment by bottler** [comment]
What is the output of `conda list` in the environment?

**Comment by yichao-liang** [comment]
Thanks for your reply! Attached below is the `conda list` output
[conda_list.txt](https://github.com/facebookresearch/pytorch3d/files/8898614/conda_list.txt)

**Comment by bottler** [comment]
Something has gone wrong with torchvision. The pytorch3d package wants torchvision at least version 0.5, but really you should have the version of torchvision which matches the version of pytorch. So for pytorch 1.9.1 that would be `0.10.something`. You have torchvision version 0.22, which means something went wrong when you tried to install torchvision. I think 0.22 is a version which is easy to install by accident, because there is a package somewhere with too loose/few dependencies. This may be because something else in the environment prevented the right torchvision to be installed.

Can you try again, being careful to see what happens when torchvision is installed?

**Comment by yichao-liang** [comment]
Thanks for noticing that! 

The install succeeded after I install `torchvision=0.10.1`. I had no idea why it automatically installed `torchvision=0.2.2` for some reason.

Thanks a lot!
