### ISSUE TITLE
Mesh extend should broadcast rather than duplicate 

### ISSUE THREAD

**Issue by justanhduc** [facebookresearch/pytorch3d#1238]
## 🚀 Feature
It is desirable for mesh extend to broadcast rather than duplicate the meshes.

## Motivation
This can save a lot of memory and unnecessary duplication.

**Comment by bottler** [comment]
This isn't possible in general in the current design, because we always have one batch dimension. It could only work when the mesh has one batch element. For creating a Meshes with one mesh repeated, the user is free to supply broadcasted tensors, which will get some of the benefit this feature would bring.
