### ISSUE TITLE
How do I run Pulsar in parallel on multiple GPUs

### ISSUE THREAD

**Issue by fhahlbohm** [facebookresearch/pytorch3d#1274]
## ❓ Running the Pulsar Renderer in parallel on multiple GPUs

I am running an iterative pipeline that requires rendering of multiple images during each iteration.
To do so, I adapted the multiview example that can be found in this repository.

Due to lack of GPU memory on a single GPU, I would like to split the load across multiple GPUs.

What I am currently trying to do is splitting the input (i.e. my camera parameters) into chunks so that my GPU memory can handle its computation. I then call the renderer for each of these chunks in a simple for loop extending my point cloud's parameter to the respective shape as shown in the multiview example. This all happens within a module that is wrapped in PyTorch's DataParallel.
I recognize that my issue likely is largely due to my inexperience with PyTorch's DataParallel. Do I need to manually set up Pulsar on every GPU I plan on using?

Ultimately, my question is whether there is a preferred way of doing this with Pulsar?
If there is, maybe this could even be added as another helpful example?

**Comment by classner** [comment]
Hi @fhahlbohm !

Each Pulsar renderer object is local to a specific device (that's why you have to place it using `.to(dev)`). It sets up acceleration structures on that specific device and will only accept tensors with matching device placement. So to use two GPUs, you're simply creating two renderers, one on each, and use them to process the respective tensors.

As far as interplay with DP is concerned (I assume you mean https://pytorch.org/docs/stable/generated/torch.nn.DataParallel.html ): you'd want to encapsulate renderer instantiation and device placement in a PyTorch module. DP replicates and places each module (consequently automatically also the renderer instance) - then it should be automatically correctly be used.

Does this help with your question?

**Comment by fhahlbohm** [comment]
Yes, the information you provided is exactly what I needed.

Thank you for your fast & precise answer!
