### ISSUE TITLE
The speed of MeshRasterizerOpenGL

### ISSUE THREAD

**Issue by Entongsu** [facebookresearch/pytorch3d#1294]
I have used MeshRasterizerOpenGL for rendering, but the speed has been not improved compared with MeshRasterizer. I am not sure whether there is any problem in using MeshRasterizerOpenGL. Thank you!

**Comment by kjchalup** [comment]
What's your use-case? It should definitely be faster if:

1) You mesh is reasonably big, and
2) You're doing multiple rendering iterations.

If the mesh is very small (hundreds or a few thousand faces), I wouldn't expect a large speedup as the rasterization step won't even be the bottleneck. But even on the cow mesh (5865 faces), I see more than 6x speedup when doing mesh optimization. On a 2M faces Nefertiti mesh I see 20x when doing pose optimization. [You can get a bunch of fun large meshes for experimentation [here](https://www.cs.cmu.edu/~kmcrane/Projects/ModelRepository/) btw.]

If you only do one iteration of rendering, you likely won't see any speedup (or even a big slowdown), because the first time the rasterizer runs it needs to compile the OpenGL program specific to the mesh size etc.

**Comment by Entongsu** [comment]
Thank you for your reply. I have run the function of test_compare_rasterizers in tests  https://github.com/facebookresearch/pytorch3d/blob/main/tests/test_rasterizer.py. I have gotten a warning "PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuGraphicsUnregisterResource failed: invalid OpenGL or DirectX context" . I am not sure how to handle this problem. I am not sure whether there is a reason of the non-improved speed of MeshRasterizerOpenGL.

**Comment by bottler** [comment]
There are still some oddities in cleanup in some of these tests. We hope to take a look sometime.
