### ISSUE TITLE
Install failed, version mismatch

### ISSUE THREAD

**Issue by zhangyulong882** [facebookresearch/pytorch3d#159]
Install failed on my Ubuntu 18.04 with python 3.7
the error message is:
pytorch3d -> python[version='>=2.7,<2.8.0a0|>=3.5,<3.6.0a0']

Can pytorch3d running with python 3.7?

**Comment by bottler** [comment]
Yes. Python 3.7 should be fine. I assume you are using conda because of the format of that message. But the message specifics are weird: the package called pytorch3d wants python 2.7 or 3.5, and that isn't right. 

Can you run `conda list` and paste the output? Are you downloading from anaconda cloud directly?

**Comment by zhangyulong882** [comment]
I used the command bellow as you metioned in another issue and succeeded:

pip install 'git+https://github.com/facebookresearch/pytorch3d.git'
