### ISSUE TITLE
Why faces_per_pixel is limited to 150?

### ISSUE THREAD

**Issue by NotAnyMike** [facebookresearch/pytorch3d#168]
#### Why faces_per_pixel is limited to 150

I have tried to run it with a higher number but it throws me an error. Can you explain why the limit is in 150? I don't think I should add the error it raise because this issue is not reporting a bug or something like that. But anyway let me know if you'd prefer it .

**Comment by nikhilaravi** [comment]
The rasterization cuda kernels in PyTorch3D output the intermediate values so that shading can be done in PyTorch (as compared to SoftRasterizer where the rasterization cuda kernel outputs an image directly). For each image pixel we keep an array of the top `faces_per_pixel` and we need to set the max size at compile time (which is currently set to 150). Is this limit causing issues for the task you are working on?
We have thought about making this a template parameter but haven't refactored the cuda kernels to support this.

**Comment by NotAnyMike** [comment]
I am still trying to figure out if this is causing issues. I was trying to understand the reason for the gap when compared to SoftRas for single view mesh reconstruction. I tried to use a higher number of faces per pixel to see if that closes the gap but it does not happen. I was wondering the reason of the 150 limit.

SoftRas propagates the signal through all the faces in the pixel, if I am not mistaken it is not limited to a certain number of faces. So the closest you can get to this would be by setting faces_per_pixel to the number of faces of the mesh. Is that right?

**Comment by jcjohnson** [comment]
SoftRas uses a monolithic CUDA kernel to iterate over every face for every pixel, in which they compute the effect of the face on the pixel. In PyTorch3D we use a more modular design, in which a rasterization kernel first outputs the faces hit by each pixel, and separate shader functions compute the final pixel values. Our design give more flexibility since new shaders can be written in Python without touching CUDA code; however if we wanted to follow SoftRas and allow each face to affect each pixel, we'd need to potentially pass a very large intermediate tensor from the rasterizer to the shaders. To avoid memory issues, we therefore impose a cap on the maximum number of faces allowed to influenced by each face.

However there's nothing special about the number 150; we chose this because we thought it would probably be enough for most use cases. Removing this restriction is one of many low-level fixes we'd like to make to the rasterization code.

As a hack, you can increase the limit by changing this constant and rebuilding from source: https://github.com/facebookresearch/pytorch3d/blob/master/pytorch3d/csrc/rasterize_points/rasterization_utils.cuh#L18

**Comment by gkioxari** [comment]
No response. Closing this. Feel free to re-open for followup questions.
