### ISSUE TITLE
number of categories cannot exceed 2^24

### ISSUE THREAD

**Issue by magicknight** [facebookresearch/pytorch3d#182]
Hi,

I have a volume data loaded from a ct-scaned volume file. 
I used cubify followed by sample_points_from_meshes to turn it to point cloud. 
However, I got a 'number of categories cannot exceed 2^24' error when I run the sample_points_from_meshes  function. 

```python

ct_mesh.verts_packed().shape

ct_pcld = sample_points_from_meshes(ct_mesh)

```
```
torch.Size([8254078, 3])
```

```

/usr/local/lib/python3.6/dist-packages/pytorch3d/ops/sample_points_from_meshes.py in sample_points_from_meshes(meshes, num_samples, return_normals)
     62         # TODO (gkioxari) Confirm multinomial bug is not present with real data.
     63         sample_face_idxs = areas_padded.multinomial(
---> 64             num_samples, replacement=True
     65         )  # (N, num_samples)
     66         sample_face_idxs += mesh_to_face[meshes.valid].view(num_valid_meshes, 1)

RuntimeError: number of categories cannot exceed 2^24

````

**Comment by gkioxari** [comment]
Hi @magicknight 
From a quick search on the internet, this seems to be a PyTorch bug, e.g. see this issue https://github.com/pytorch/pytorch/issues/2576.  You should comment on the issue so that PyTorch fixes it. 

As a workaround the bug, you could try to reduce the size of your mesh. Your current mesh has over 8M vertices. That is a huge mesh!! Maybe you could try to reduce the size of your voxel before running it through cubify or reduce the size of the mesh some other way.

**Comment by gkioxari** [comment]
Hi @magicknight 
I am closing this issue for now hoping that the PyTorch team adds support for more categories. Feel free to re-open if anything emerges.
