### ISSUE TITLE
Support for .off mesh files

### ISSUE THREAD

**Issue by jibrilmuhammadadam** [facebookresearch/pytorch3d#216]
## 🚀 Feature

NOTE: Please look at the existing list of Issues tagged with the label ['enhancement`](https://github.com/facebookresearch/pytorch3d/issues?q=label%3Aenhancement). **Only open a new issue if you do not see your feature request there**.

## Motivation
Hi, I have a huge amount of mesh data (in .off format) and would like to use Pytorch3D to process it because it has most of the functions I want. Are you adding support for .off mesh file?

## Pitch
Do you think I can modify the functionalities of .ply format (in Pytorch3D) to work on .off format? Because .ply structure is closer to .off than .obj
Thank you.

NOTE: we only consider adding new features if they are useful for many users.

**Comment by gkioxari** [comment]
Hi @jibrilmuhammadadam 
Supporting .off would be great. If you would like to submit a PR that supports load and save functionality for .off files we would be more than happy to review it.

**Comment by raincrash** [comment]
I would like to work on adding .off io if @jibrilmuhammadadam or anyone else isn't already working on it.

**Comment by jibrilmuhammadadam** [comment]
I am not working at it @raincrash . You can work on it, it will be of great help. Thanks.

**Comment by gkioxari** [comment]
@raincrash that's exciting!!
When adding a new feature to PyTorch3D, please follow our guidelines which can be found here
https://github.com/facebookresearch/pytorch3d/blob/master/.github/CONTRIBUTING.md

**Comment by raincrash** [comment]
Hi, @gkioxari @nikhilaravi, I have a quick question on the design of the `io` module, do you recommend preserving the same structure for the other files - `ply_io.py` and `obj_io.py` and adding a new `off_io.py` file, or refactor the module to support offs? I am asking because the off support can use some private functions of `ply_io` and will have some formatting and property (eg ASCII-only) differences.

**Comment by nikhilaravi** [comment]
@raincrash have you already started working on `.off` support? We are happy to work on this internally if not.

**Comment by raincrash** [comment]
@nikhilaravi I have just started adding `load_off` calls and the `raw` version of it and realized it would make more sense to refactor `ply_io` to support more input/output types other than `obj`. But I wasn't sure if I should change the `ply_io` since it has dependencies across. I can try working on this if there is a clearer way on how to handle this. If there is another good-first-issue, I am happy to do that instead as well. :)

**Comment by bottler** [comment]
I am happy to make this change and I intend to do it soon. If you have done a lot on it and want to make a PR please do so by the end of September.

**Comment by bottler** [comment]
The ascii OFF format is clear to me, and I can see datasets which use it, but I cannot find examples of binary OFF files. I am wondering if anyone has examples of the binary version?

**Comment by albertotono** [comment]
I think occupancy network used that .off file format. Hope it can help.

**Comment by bottler** [comment]
This has just landed in https://github.com/facebookresearch/pytorch3d/commit/0345f860d4d44e0a36b3a366644f6432458ae5cc . I am closing this issue.
