### ISSUE TITLE
How do I do 3D transform from  world coordinates to the camera coordinates like neural-render with PyTorch3D？

### ISSUE THREAD

**Issue by leoyzhang** [facebookresearch/pytorch3d#238]
Now I have a camera extrinsic(R and T).
When I use the neural_render(https://github.com/daniilidis-group/neural_renderer) to transform and render, the code:
```python
import neural_renderer as nr
renderer = nr.Renderer(image_size=render_size, camera_mode='projection',near=0, far=10000,
                                    light_intensity_ambient=1.0, light_intensity_directional=0,
                                    light_color_ambient=[1,1,1], light_color_directional=[1,1,1],
                                    light_direction=[0,1,0], anti_aliasing=True)

images = renderer(cur_mesh, gt_faces, textures=textures_iuv, mode='rgb', K=cam_K, R=cam_R, t=cam_T, orig_size=512)
```
And the 3D mesh in the camera coordinate:
![image](https://user-images.githubusercontent.com/26193836/84870432-e8d20780-b0b1-11ea-8897-6480878ce4b9.png)

But when I use pytorch3d to transform and render with the same camera extrinsic(R and T), the result is wrong:
```python
focal_length = torch.zeros(1,2).cuda()
principal_point = torch.zeros(1,2).cuda()
focal_length[0, 0] = cam_K[0, 0, 0]
focal_length[0, 1] = cam_K[0, 1, 1]
principal_point[0, 0] = cam_K[0, 0, 2]
principal_point[0, 1] = cam_K[0, 1, 2]
cameras = SfMPerspectiveCameras(device=device, R=cam_R, T=cam_T, focal_length = focal_length, principal_point = principal_point)

raster_settings = RasterizationSettings(
            image_size=512, 
            blur_radius=0.0, 
            faces_per_pixel=1,
)

lights = PointLights(device=device, location=[[0, 0, 0]])

renderer = MeshRenderer(
    rasterizer=MeshRasterizer(
        cameras=cameras, 
        raster_settings=raster_settings,
    ),
    shader=TexturedSoftPhongShader(
        device=device, 
        cameras=cameras,
        lights=lights
    )
)
images = renderer(mesh)
```
the 3D mesh in the camera coordinate:
![image](https://user-images.githubusercontent.com/26193836/84869507-b542ad80-b0b0-11ea-9c8e-b794c03e47e5.png)

So how do I do 3D transform with Pytorch3D to get the same result as neural-render?

**Comment by gkioxari** [comment]
The camera coordinate systems between NMR and PyTorch3D might be completely different. So you need to check that and make sure that your R and T are consistent with our world coordinate system.

**Comment by Eckert-ZJB** [comment]
Did you solved this issue? How did you do to make the R&T consistent with the coordinate of pytorch3d system?

**Comment by leoyzhang** [comment]
> Did you solved this issue? How did you do to make the R&T consistent with the coordinate of pytorch3d system?

I solved this issue by changing the source code of pytorch3d to make the R&T consistent with NMR.

**Comment by gkioxari** [comment]
It's great you folks fixed it but let me suggest a few things and give you my 2cents. 
The best way to set yourself up for research and development is to understand what each tool does and what it assumes. When working with 3D data and 3D tools, it's crucial to understand what the world coordinate system is supposed to be and what transforms occur and under what convention. Note that there is a few coordinate systems involved in rendering pipelines, namely world coordinate system, NDC and screen space. NMR is making their assumptions on those, OpenGL makes their own assumptions, SoftRas makes their own assumptions and of course we make our own assumptions. All these assumptions don't have to agree with each other and in fact they don't. Now, if you want to build on top of a library without any bugs, it's best to understand these assumptions as best as possible. Surely, you can change the source code in a particular file to do what you want it to do, but to me that sounds like a source of bugs down the line because you changed a part of the library but the rest of the library is still making the same assumptions which you haven't changed. So changing the R&T to be consistent with NMR in part of the code is to me the wrong way to go about things. Ultimately, it's up to you what you do but wanted to let you know of what I think.

**Comment by nikhilaravi** [comment]
@leoyzhang were you able to solve your problem? Can we close this issue?
