### ISSUE TITLE
Failed to build wheel in Nvidia CUDA 10.1 Ubuntu 16.04 Docker image

### ISSUE THREAD

**Issue by MiroPsota** [facebookresearch/pytorch3d#284]
## Instructions To Reproduce the Issue:
Build [Dockerfile](https://github.com/facebookresearch/pytorch3d/files/4965856/Dockerfile.txt) and run commands in [build_wheel_pytorch3d.sh](https://github.com/facebookresearch/pytorch3d/files/4965862/build_wheel_pytorch3d.sh.txt).

## Relevant error:
Parts with errors in [error.log](https://github.com/facebookresearch/pytorch3d/files/4965907/error.log) and full log in [full.log](https://github.com/facebookresearch/pytorch3d/files/4965969/full.log).

## Notes:
I can build pytorch3d wheel with `cuda 10.1 Ubuntu 18.04` and `cuda 11.0 Ubuntu 20.04` as base images so it's likely some incompatibility with GCC 5.4?
Also buildable with `cuda 10.1 Ubuntu 16.04` at commit dc08c30583085bfbd818f0bc07124c34b095c5c4.

**Comment by bottler** [comment]
This is the problem with cloneable not working in nvcc. It can be fixed by making a change like https://github.com/facebookresearch/pytorch3d/commit/85c396f822aab9dbcfde12a7cf535402d831794d to the code recently added in https://github.com/facebookresearch/pytorch3d/commit/bce396df93e338cc0d35256d650a3b6ab3f8b973.

With pytorch master I think this won't be a problem because of a fix like https://github.com/pytorch/pytorch/pull/37221. It also might be working with latest pytorch (1.5.1) rather than the 1.5.0 which you might be picking up - I'm not sure about this.

**Comment by MiroPsota** [comment]
I confirm it's building with pytorch 1.5.1. I suggest to add note to `install.md`. You can close this issue.
