### ISSUE TITLE
Inferring UV maps

### ISSUE THREAD

**Issue by christopher-beckham** [facebookresearch/pytorch3d#286]
Hi,

I'm quite new to PyTorch3D, and I've been searching around for a bit trying to find the answer (to no avail), so here goes.

The question I have is in the context of some of the more recent papers I have seen that try to infer (simultaneously) the mesh, texture, and camera based on a single image or several images. In particular, I am interested in a simple use case where you have to infer a texture for a mesh. This would also involve inferring the UV map for it (which, in this case, would be `verts_uvs`, a `(N, V, 2)` tensor). I understand that in traditional 3D modelling applications, it can automatically generate a UV map for a mesh by doing some sort of unfolding (like [this](https://i.ytimg.com/vi/Z4BXfTl6IcQ/maxresdefault.jpg)) but I am not sure how one would go about this in PyTorch3D. I imagine that maybe there is an algorithm (or algorithms) that can map the vertex/faces of a mesh to a flat plane but I don't see any functionality for this in the library.

The alternative would be to import a mesh (i.e. an obj file) with the UV map already defined, but then I am not sure how this would work with some recent papers I have seen where the mesh is simultaneously optimised with the texture. For example, in this [recent paper](https://arxiv.org/abs/2007.10982) the authors infer vertex offsets for a template mesh + texture + camera. In that case, since the vertex offsets are being iteratively updated, it seems like you would also have to iteratively update the corresponding UV map (which I assume is also learned).

Anyways, I hope this all makes sense.

Thanks again for all the great work you've done on this library.

**Comment by gkioxari** [comment]
Hi @christopher-beckham 
Your question seems to be a RnD related question and not a specific issue with the library like a bug. Unfortunately, we don't have the bandwidth to address and support research questions and consult for projects, otherwise that's all we would be doing with our time. I apologize for this response. If you do come up with concrete bugs then we are more than happy to help fix them if they are associated with compact and concise reproducible code.
