### ISSUE TITLE
HBox(children=(IntProgress(value=0, max=2000), HTML(value=''))) error

### ISSUE THREAD

**Issue by jin0kim** [facebookresearch/pytorch3d#314]
## 🐛 Bugs / Unexpected behaviors

1. Any changes you made (`git diff`) or code you wrote
```
convert ipynb to py (via jupyter notebook)
```
2. The exact command(s) you ran:

docs/tutorials 
fit_textured_mesh
camera_position_optimization_with_differentiable_rendering

3. What you observed (including the full logs):
```
/pytorch/aten/src/ATen/native/BinaryOps.cpp:81: UserWarning: Integer division of tensors using div or / is deprecated, and in a future release div will perform true division as in Python 3. Use true_divide or floor_divide (// in Python) instead.
HBox(children=(IntProgress(value=0, max=2000), HTML(value='')))
```

python=3.6.6 pytorch =1.5 torchvision=0.6
pytorch3d was installed from pypi packages 
'''
pip install pytorch3d-0.2.0-cp36-cp36m-manylinux1_x86_64.whl
'''

**Comment by bottler** [comment]
You haven't shown the whole error here, but I can guess what might be happening.
The commands `HBox` and `HTML` are specific to jupyter notebooks. My guess is that they are called by the part of tqdm we are using - where we explicitly use the notebook version because the tutorials are a notebook 🙂. As you want to run this outside of a notebook, you can remove the references to tqdm or replace it with a simple call to `tqdm.tqdm`.

**Comment by jin0kim** [comment]
> You haven't shown the whole error here, but I can guess what might be happening.
> The commands `HBox` and `HTML` are specific to jupyter notebooks. My guess is that they are called by the part of tqdm we are using - where we explicitly use the notebook version because the tutorials are a notebook 🙂. As you want to run this outside of a notebook, you can remove the references to tqdm or replace it with a simple call to `tqdm.tqdm`.

Yes I could solve this problem that changes import references
'from tqdm.notebook import tqdm'
to
'from tqdm import tqdm'
