### ISSUE TITLE
Why not use reshape here?

### ISSUE THREAD

**Issue by CharlesNord** [facebookresearch/pytorch3d#328]
https://github.com/facebookresearch/pytorch3d/blob/f03aa5803bcdba3b9447a8c2ffdc77e693d51c87/pytorch3d/structures/meshes.py#L1038

face_to_edge = inverse_idxs.reshape(3, N).t()

**Comment by jcjohnson** [comment]
If the input tensor is contiguous, then `view` and `reshape` do the exact same thing. In this case, the output from `torch.arange` is a new tensor guaranteed to be contiguous, so `view` and `reshape` will the give the same result; then I prefer `view` since it's shorter.

More generally, `view` is guaranteed to return a view of the input tensor; in contrast `reshape` returns a view if possible, and if not then returns a copy. I often prefer `view` since it makes it more explicit when copies of tensors are being made; this can make it easier to get a sense of where memory is being allocated, in case you later need to optimize memory usage.

**Comment by gkioxari** [comment]
I think this could be correct! @CharlesNord if you find that this change provides speedup or memory improvement could you provide this info here and we will incorporate the change

**Comment by nikhilaravi** [comment]
@CharlesNord would you like to submit a pull request for this change?
