### ISSUE TITLE
A question about using PyTorch3D in GPU server (logged in with SSH)

### ISSUE THREAD

**Issue by XiaoqiangZhou** [facebookresearch/pytorch3d#361]
Hi,

I hear from a friend that PyTorch3D is a pure python render tool. I also think this project is excellent.

However, I want to know if I can use pytorch3d in a gpu server, which I usually log in with SSH connection. Is pytorch3d capable of returning renderer result through the ssh connection in a real-time manner? Is there any documents for this problem?

Thanks!

**Comment by gkioxari** [comment]
Hi @XiaoqiangZhou 
I don't quite understand your question. PyTorch3D runs in any machine as long as you build PyTorch3D. 
If that is not the case, can you report back with a concrete bug or installation issue so that we can help address your problem? I will be closing this task but feel free to reopen once you run into issues.
