### ISSUE TITLE
ImportError Symbol not found

### ISSUE THREAD

**Issue by jasonshi10** [facebookresearch/pytorch3d#377]
v## 🐛 Bugs / Unexpected behaviors
ImportError Symbol not found: __ZN2at23getLegacyDeviceTypeInitEv

## Instructions To Reproduce the Issue:

1. Any changes you made (`git diff`) or code you wrote
 No.

2. The exact command(s) you ran:
```
from pytorch3d.io import load_obj, save_obj
```
3. What you observed (including the full logs):
```
ImportError: dlopen(/Users/miniconda3/envs/graphein/lib/python3.7/site-packages/pytorch3d/_C.cpython-37m-darwin.so, 2): Symbol not found: __ZN2at23getLegacyDeviceTypeInitEv
  Referenced from: /Users/miniconda3/envs/graphein/lib/python3.7/site-packages/pytorch3d/_C.cpython-37m-darwin.so
  Expected in: /Users/miniconda3/envs/graphein/lib/python3.7/site-packages/torch/lib/libtorch_cpu.dylib
 in /Users/miniconda3/envs/graphein/lib/python3.7/site-packages/pytorch3d/_C.cpython-37m-darwin.so
```

4. Additional info may be helpful:
I'm using torch 1.6.0 and pytorch3d 0.2.0, installed on Mac laptop. Here's what I installed for torch geometric.

```
pip install torch-scatter==latest+cpu -f https://pytorch-geometric.com/whl/torch-1.6.0.html
pip install torch-sparse==latest+cpu -f https://pytorch-geometric.com/whl/torch-1.6.0.html
pip install torch-cluster==latest+cpu -f https://pytorch-geometric.com/whl/torch-1.6.0.html
pip install torch-spline-conv==latest+cpu -f https://pytorch-geometric.com/whl/torch-1.6.0.html
pip install torch-geometric
```

Would appreciate if you can point me to the right direction. Thanks!

**Comment by nikhilaravi** [comment]
This looks like an issue with the CUDA. What version of CUDA are you using?

**Comment by bottler** [comment]
**Note that this issue and what I write here is mac specific.**

pytorch3d has to be built for a particular version of pytorch. You are getting this error because of a mismatch between the version with which pytorch3d has been built and the version of pytorch (or one of them) you have in your environment.

If you are using the package from pypi (i.e. `pip install pytorch3d`) then there is only one right version of pytorch. The packages from latest version of pytorch3d (0.2.5) match the latest version of pytorch (1.6.0). The packages from version 0.2.0 of pytorch3d use pytorch 1.5.0.

**Comment by jasonshi10** [comment]
Hi Jeremy,

I used torch 1.5.0 and pytorch3d 0.2.0 and the import error has been resolved. Thank you!
