### ISSUE TITLE
Interpolating Vertices Attributes

### ISSUE THREAD

**Issue by pranny** [facebookresearch/pytorch3d#380]
## ❓ How to go about barycentric interpolation of vertex attributes?

I am doing an implementation where certain attributes are associated with vertices. An example could be Basel face model, where the shape, identity or expression basis are represented per vertex. I am using PyTorch3D for this implementation. Currently, this library only face attributes' interpolation. Do you have any such API for vertices in the roadmap?

**Comment by gkioxari** [comment]
Could you give us an example of what you wish to do? I don't quite understand. We have code for face interpolation with barycentric coordinates because that is a very common use case. There, vertex attributes are interpolated for points on mesh faces using barycentric coordinates and following the linear interpolation rule.

**Comment by pranny** [comment]
I understand now. I am looking for the same functionality, but was expecting a different API. This API makes more sense now.

**Comment by pranny** [comment]
I started my implementation, and the API struck me again. Here's more detail about it.

I am trying to implement a process, where a [Basel Face Model (bfm) ](https://faces.dmi.unibas.ch/bfm/)is manipulated to generate new shapes, by altering it's identity (`I`) and expression (`E`) parameters. 

- bfm is represented as vertices `(V, )`, triangles `(T, 3)` and attributes associated with each vertex. Ex: Position for each vertex represented as `(3, V)`, and similarly other attributes as `(I, V)` and `(E, V)`.
- Pytorch DatasetLoader loads a batch of identity `(B, I, V)` and exp `(B, E, V)` params. I use them to compute new position of vertices in the batch, making position `(B, V, 3)`
- Repeat triangles (since they don't change in this case), and resize to make it compatible to `(B, T, 3)`
- I use Meshes API to create a batch of meshes using above triangles and vertices
- Perform rasterization on above meshes object and get pix_to_face `(B, h, w, K)`, barycentric `(B, h w, K, 3)`, `K` = Faces per pixel
- For each pixel, bary. interp. to get avg position params. So, my input to `interpolate_face_attributes`'s 3rd parameter should be `(T, 3, D=3)`. This seems to assume that every batch will go with the same value of vertices' attributes, which is not valid in this case. So, I think there should be another API that has the batch face attrs as it's param, of shape `(B, T, 3, D)`

**Comment by nikhilaravi** [comment]
@pranny the 3rd parameter to `interpolate_face_attributes` is  `face_attributes ` which is of shape `(total_faces, 3, D)`.  In your case `total_faces = B * T`.  

After rasterization the indices in  `pix_to_face`  refer to the indices in `meshes.faces_packed()`. This represents the flattened list of the faces in the mesh i.e. `(total_faces, 3)` not `(batch_size, num_faces, 3)`. 

To get the correct output from `interpolate_face_attributes` you need to reshape the face attributes from `(B, T, 3, D)` to `(total_faces, 3, D)`. 

For example:
```
from pytorch3d.structures import padded_to_packed

# Starting with vertex_features with shape (N, V, D)
split_sizes = meshes.num_verts_per_mesh()  # (N, )
vertex_features_packed = padded_to_packed(vertex_features, split_sizes)   # (sum(split_sizes), D)

face_attributes = vertex_features_packed[meshes.faces_packed(), ...]

# face_attributes will be of  shape (total_faces, 3, D) where D is the dimension of the feature. 
```

**Comment by gkioxari** [comment]
Hi @pranny 
Note that the github issues should be used for concrete bug reports or feature requests. In both cases, the description should be accompanied with a compact code snippet that will help us reproduce your bug or understand your feature request. 

Your question here seems to not be a bug report nor a feature request but you are asking us how to implement your particular computation in PyTorch3D. It's very nice of Nikhila that she is helping out but note that we will not be responding  to such questions promptly as we don't have the capacity to be consultants for people's projects. Otherwise, that's what we would do all day.
