### ISSUE TITLE
Made a bunch of methods of `Pointclouds` class properties

### ISSUE THREAD

**Issue by justanhduc** [facebookresearch/pytorch3d#389]
## 🚀 Feature

Many methods in the `Pointclouds` class can be made properties. For e.g., `points_packed` and `points_packed` are among these methods.

## Motivation

- To get rid of the annoying parentheses.
- To prevent from "accidentally" overwrite the points, normals, and features.
- IMO, points, features and normals are "properties" rather than "methods"

## Pitch

```
p = Pointclouds(...)
points_padded = p.points_padded()  # current interface
points_padded = p.points_padded  # new interface
```

## PR

If the request is granted, I would be happy to send a PR.

**Comment by jcjohnson** [comment]
Hi @justanhduc, thanks for the suggestion! We actually considered this when we originally designed the `Pointclouds` and `Meshes` classes (and I think even had an internal version implemented in this way before the first public release). 

However we ultimately decided to stick with methods instead of properties. Even though they are conceptually similar to a property, methods like `points_packed` can involve nontrivial computation and may even build part of a computational graph depending on the current state of the object. Property lookup should not in general involve side effects, so we felt that keeping them as methods makes the potential for side effects more clear to users and that this outweighs the minor syntactic clutter of typing an extra pair of parenthesis.
