### ISSUE TITLE
TextureAtlas V.S TextureUV

### ISSUE THREAD

**Issue by LuckyDC** [facebookresearch/pytorch3d#398]
Original SoftRas and NMR implementation use atlas texture representation.
Pyotorch3d provides two texture representation TextureAtlas and TextureUV.
Is there any difference between them during the gradient computation in back-propagation?
Would they lead to the same result if I respectively use them to optimize photometric loss of the rendered image?
How to convert the two types of texture?

**Comment by gkioxari** [comment]
PyTorch3D provides three texture types `TexturesAtlas`, `TexturesUV` and `TexturesVertex`. They are all different representations and require textures to be encoded differently. Each texture representation has a `sample_textures` method which computes textures for each vertex or face on a mesh. The output of this function is used for rendering.

Since they are different representations they also lead to different optimization most likely. You should use the texture type that is most relevant to your research problem. Please read the code and our tutorials.

**Comment by LuckyDC** [comment]
Thanks for your reply. And how to convert between TextureUV and TextureAtlas?

**Comment by ck-amrahd** [comment]
Is there a way to convert TextureAtlas into TextureUV? Thank you.

**Comment by Jiakui** [comment]
Can we optimize the texture via  TextureUV, or, is it differeciable ?
