### ISSUE TITLE
How can I replace a texture ?

### ISSUE THREAD

**Issue by elcronos** [facebookresearch/pytorch3d#402]
I am new to 3d rendering so I might be a bit confused with some concepts. But this is what I want to do:

1. Get the original texture of the textured object that I loaded as an RGB Image.
2. Modify that texture by adding a patch to it.
3. Replace the original texture with the new one on the mesh.

The code below allow me to get the RGB Image and then modify it. I just do not understand how to change the original by the new one on the mesh. I hope the code makes sense.

```
def display_texture(texture, fig_size=5):
    plt.figure(figsize=(fig_size,fig_size))
    plt.imshow(texture.squeeze().cpu().numpy())
    plt.grid("off");
    plt.axis('off');
    plt.show()
    
def add_patch_texture(texture, p, x_l, y_l):
    patch = torch.zeros_like(texture)
    mask = torch.ones_like(texture)
    size_patch = p.shape[1]
    patch[:,y_l:y_l+size_patch,x_l:x_l+size_patch,:] = p
    mask[:,y_l:y_l+size_patch,x_l:x_l+size_patch,:]  = 0
    return (mask*texture) + patch

obj_filename = os.path.join(DATA_DIR, "lexus/lexus.obj")
# Load obj file
mesh = load_objs_as_meshes([obj_filename], device=device)

# 1. Get Original Texture
display_texture(texture_image)
texture_image=mesh.textures.maps_padded()

# New Texture
size_patch = 60
x_l = 500
y_l = 450
print('Patch')
p = torch.rand((size_patch,size_patch,3))
plt.imshow(p.numpy())
plt.show()
# 2. Create New Texture
applied_patch = add_patch_texture(texture_image,p, x_l, y_l)[0]
display_texture(applied_patch)

# 3. Replace old texture in original mesh??
```

**Comment by gkioxari** [comment]
Hi @elcronos 

I replied on another issue where you posted the same question. To repeat, we document all our texture types in quite a lot of detail in [textures.py](https://github.com/facebookresearch/pytorch3d/blob/master/pytorch3d/renderer/mesh/textures.py). Since you are new to rendering, I recommend that you read through this file and familiarize yourself with all the different texture types there are for meshes. I think this will be very helpful for you and will get you to the solution of your problem. 

Since you are new to a problem, I really advise you to read as much as you can and understand the concepts. There is no way you can solve any problems if you don't take the time to understand and gather knowledge. 

Finally, note that the github issues for this project refer to bug issues or enhancement requests. We would love to help you all with your research questions, but unfortunately we can't do this as then we would spend all our time being consultants to people's projects.
