### ISSUE TITLE
Formal definition of `point_mesh_face_distance`

### ISSUE THREAD

**Issue by luost26** [facebookresearch/pytorch3d#410]
Hi,

I wonder what is the formal definition (mathematical formulas) of `pytorch3d.loss.point_mesh_face_distance`.

I checked the documentation and only found limited details about it. I will appreciate it if someone could give the formal definition or the reference to related papers that define the `point_mesh_face_distance`.

**Comment by gkioxari** [comment]
The function computes distances between a point `p` in 3D space and a face `f` in 3D space. The definitions for are derived from geometry and can be broken into the following:
Assume `p0` is the projection of `p` onto the plane defined by `f`
* If `p0` falls within `f`, then the distance is `||p-p0||`
* Otherwise, it is the distance from the closes edge of `f`.

All this can be found in our geometry util functions ([geometry_utils.h](https://github.com/facebookresearch/pytorch3d/blob/master/pytorch3d/csrc/utils/geometry_utils.h) and [geometry_utils.cuh](https://github.com/facebookresearch/pytorch3d/blob/master/pytorch3d/csrc/utils/geometry_utils.cuh))
