### ISSUE TITLE
Installing Pytorch3d from github in Google Colab

### ISSUE THREAD

**Issue by Poufy** [facebookresearch/pytorch3d#427]
I am simply trying to install pytorch3D on colab to test it out.  I tried the two followings commands in a block.

```
!pip install torch torchvision
!pip install 'git+https://github.com/facebookresearch/pytorch3d.git'
```
I also tried to replace 
```
!pip install 'git+https://github.com/facebookresearch/pytorch3d.git'
``` 
with
```
!pip install 'git+https://github.com/facebookresearch/pytorch3d.git@stable'
``` 
but I still get the same issue. Its stuck on "Building wheels for collected packages: pytorch3d, fvcore, pyyaml"

Logs:
Requirement already satisfied: torch in /usr/local/lib/python3.6/dist-packages (1.7.0+cu101)
Requirement already satisfied: torchvision in /usr/local/lib/python3.6/dist-packages (0.8.1+cu101)
Requirement already satisfied: dataclasses in /usr/local/lib/python3.6/dist-packages (from torch) (0.7)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.6/dist-packages (from torch) (3.7.4.3)
Requirement already satisfied: numpy in /usr/local/lib/python3.6/dist-packages (from torch) (1.18.5)
Requirement already satisfied: future in /usr/local/lib/python3.6/dist-packages (from torch) (0.16.0)
Requirement already satisfied: pillow>=4.1.1 in /usr/local/lib/python3.6/dist-packages (from torchvision) (7.0.0)
Collecting git+https://github.com/facebookresearch/pytorch3d.git
  Cloning https://github.com/facebookresearch/pytorch3d.git to /tmp/pip-req-build-j4cc39hy
  Running command git clone -q https://github.com/facebookresearch/pytorch3d.git /tmp/pip-req-build-j4cc39hy
Requirement already satisfied: torchvision>=0.4 in /usr/local/lib/python3.6/dist-packages (from pytorch3d==0.2.5) (0.8.1+cu101)
Collecting fvcore
  Using cached https://files.pythonhosted.org/packages/e7/37/82dc217199c10288f3d05f50f342cb270ff2630841734bdfa40b54b0f8bc/fvcore-0.1.2.post20201104.tar.gz
Requirement already satisfied: torch==1.7.0 in /usr/local/lib/python3.6/dist-packages (from torchvision>=0.4->pytorch3d==0.2.5) (1.7.0+cu101)
Requirement already satisfied: pillow>=4.1.1 in /usr/local/lib/python3.6/dist-packages (from torchvision>=0.4->pytorch3d==0.2.5) (7.0.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.6/dist-packages (from torchvision>=0.4->pytorch3d==0.2.5) (1.18.5)
Collecting yacs>=0.1.6
  Using cached https://files.pythonhosted.org/packages/38/4f/fe9a4d472aa867878ce3bb7efb16654c5d63672b86dc0e6e953a67018433/yacs-0.1.8-py3-none-any.whl
Collecting pyyaml>=5.1
  Using cached https://files.pythonhosted.org/packages/64/c2/b80047c7ac2478f9501676c988a5411ed5572f35d1beff9cae07d321512c/PyYAML-5.3.1.tar.gz
Requirement already satisfied: tqdm in /usr/local/lib/python3.6/dist-packages (from fvcore->pytorch3d==0.2.5) (4.41.1)
Collecting portalocker
  Using cached https://files.pythonhosted.org/packages/89/a6/3814b7107e0788040870e8825eebf214d72166adf656ba7d4bf14759a06a/portalocker-2.0.0-py2.py3-none-any.whl
Requirement already satisfied: termcolor>=1.1 in /usr/local/lib/python3.6/dist-packages (from fvcore->pytorch3d==0.2.5) (1.1.0)
Requirement already satisfied: tabulate in /usr/local/lib/python3.6/dist-packages (from fvcore->pytorch3d==0.2.5) (0.8.7)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.6/dist-packages (from torch==1.7.0->torchvision>=0.4->pytorch3d==0.2.5) (3.7.4.3)
Requirement already satisfied: dataclasses in /usr/local/lib/python3.6/dist-packages (from torch==1.7.0->torchvision>=0.4->pytorch3d==0.2.5) (0.7)
Requirement already satisfied: future in /usr/local/lib/python3.6/dist-packages (from torch==1.7.0->torchvision>=0.4->pytorch3d==0.2.5) (0.16.0)
Building wheels for collected packages: pytorch3d, fvcore, pyyaml

**Comment by bottler** [comment]
1) The build can take a very long time - several minutes. I think it might not really be stuck, it might just be in progress.

2) You should be able to use prebuilt wheels in colab, which match the stable version. Torch and torchvision are already present in colab. Just use `pip install pytorch3d` - which is what the tutorials do. Specifically, they have
```
if torch.__version__=='1.6.0+cu101' and sys.platform.startswith('linux'):
    !pip install pytorch3d
else:
    !pip install 'git+https://github.com/facebookresearch/pytorch3d.git@stable'
```
and you should find the condition passes on colab.

**Comment by Poufy** [comment]
Hi. The ``` pip install pytorch3d `` worked thanks but I really would like to build it from github. 
I running this block in google colab

```
%env FORCE_CUDA=1
!pip install -U torch==1.5 torchvision==0.6 -f https://download.pytorch.org/whl/cu101/torch_stable.html 
!pip install pyyaml==5.1 pycocotools>=2.0.1
!pip install -U fvcore
!pip install detectron2==0.1.3 -f https://dl.fbaipublicfiles.com/detectron2/wheels/cu101/torch1.5/index.html
!pip install 'git+https://github.com/facebookresearch/pytorch3d.git'
 
```
I let it run for a few minutes and it gave me this error.


Collecting git+https://github.com/facebookresearch/pytorch3d.git
  Cloning https://github.com/facebookresearch/pytorch3d.git to /tmp/pip-req-build-nr7haeiw
  Running command git clone -q https://github.com/facebookresearch/pytorch3d.git /tmp/pip-req-build-nr7haeiw
Requirement already satisfied: torchvision>=0.4 in /usr/local/lib/python3.6/dist-packages (from pytorch3d==0.2.5) (0.6.0+cu101)
Requirement already satisfied: fvcore in /usr/local/lib/python3.6/dist-packages (from pytorch3d==0.2.5) (0.1.2.post20201104)
Requirement already satisfied: torch==1.5.0 in /usr/local/lib/python3.6/dist-packages (from torchvision>=0.4->pytorch3d==0.2.5) (1.5.0+cu101)
Requirement already satisfied: pillow>=4.1.1 in /usr/local/lib/python3.6/dist-packages (from torchvision>=0.4->pytorch3d==0.2.5) (7.0.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.6/dist-packages (from torchvision>=0.4->pytorch3d==0.2.5) (1.18.5)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.6/dist-packages (from fvcore->pytorch3d==0.2.5) (5.1)
Requirement already satisfied: tqdm in /usr/local/lib/python3.6/dist-packages (from fvcore->pytorch3d==0.2.5) (4.41.1)
Requirement already satisfied: tabulate in /usr/local/lib/python3.6/dist-packages (from fvcore->pytorch3d==0.2.5) (0.8.7)
Requirement already satisfied: termcolor>=1.1 in /usr/local/lib/python3.6/dist-packages (from fvcore->pytorch3d==0.2.5) (1.1.0)
Requirement already satisfied: portalocker in /usr/local/lib/python3.6/dist-packages (from fvcore->pytorch3d==0.2.5) (2.0.0)
Requirement already satisfied: yacs>=0.1.6 in /usr/local/lib/python3.6/dist-packages (from fvcore->pytorch3d==0.2.5) (0.1.8)
Requirement already satisfied: future in /usr/local/lib/python3.6/dist-packages (from torch==1.5.0->torchvision>=0.4->pytorch3d==0.2.5) (0.16.0)
Building wheels for collected packages: pytorch3d
  Building wheel for pytorch3d (setup.py) ... error
  ERROR: Failed building wheel for pytorch3d
  Running setup.py clean for pytorch3d
Failed to build pytorch3d
Installing collected packages: pytorch3d
    Running setup.py install for pytorch3d ... error
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-nr7haeiw/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-nr7haeiw/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-ygtojicc/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.

**Comment by bottler** [comment]
In general:
It would be interesting to know why you want to build from source inside colab? It is hard to edit the sources for the binary part of pytorch3d from colab itself

I think it would be useful to work out how to see the logs? It might be that you can see them in the build directory (in this case `/tmp/pip-req-build-nr7haeiw`.

In this specific case:
You are installing from the bleeding edge / master, which currently has complications in building, such that I think I know what the error might be. The bleeding edge version requires cub (as mentioned in *its* INSTALL.md) which you appear not to have downloaded. But even fixing that there are complications.

If you really need to build from source but don't need the bleeding edge, I really think you should prefer the stable version.

**Comment by Poufy** [comment]
Yeah I actually tried installed CUB and still ran into some complications. Honestly, there is nothing to it I was just curious why it wasn't working. I just used the stable version with ``` pip install pytorch3D ``` and everything is working fine. I appreciate your time.

**Comment by mkkiy** [comment]
I want to run a demo of mesh r-cnn on provided colab. I tried the same thing and had the same problem. It does not work with the following operations. Can you tell me what kind of operation should be added?

`# install dependencies: (use cu101 because colab has CUDA 10.1)
%env FORCE_CUDA=1
!pip install -U torch==1.5 torchvision==0.6 -f https://download.pytorch.org/whl/cu101/torch_stable.html 
!pip install pyyaml==5.1 pycocotools>=2.0.1
!pip install -U fvcore
!pip install detectron2==0.1.3 -f https://dl.fbaipublicfiles.com/detectron2/wheels/cu101/torch1.5/index.html
!pip install 'git+https://github.com/facebookresearch/pytorch3d.git'`

Changes I tried

`# install dependencies: (use cu101 because colab has CUDA 10.1)
%env FORCE_CUDA=1
!pip install -U torch==1.5 torchvision==0.6 -f https://download.pytorch.org/whl/cu101/torch_stable.html 
!pip install pyyaml==5.1 pycocotools>=2.0.1
!pip install -U fvcore
!pip install detectron2==0.1.3 -f https://dl.fbaipublicfiles.com/detectron2/wheels/cu101/torch1.5/index.html

import os
!curl -LO https://github.com/NVIDIA/cub/archive/1.10.0.tar.gz
!tar xzf 1.10.0.tar.gz
os.environ["CUB_HOME"] = os.getcwd() + "/cub-1.10.0"
!pip install 'git+https://github.com/facebookresearch/pytorch3d.git@stable'`

このコマンドも試しましたところインストールはできましたが，mesh r-cnnのdemoのブロックでエラーが起きました．下記に示します．

`# Running Demo on random image of the pix3d dataset, change according to your need (change 'test.jpg' to your file name)
# Be sure to upload the file on the correct folder

!python ./meshrcnn/demo/demo.py --config-file ./meshrcnn/configs/pix3d/meshrcnn_R50_FPN.yaml \
--input /content/1.jpg --output output_demo --onlyhighest MODEL.WEIGHTS meshrcnn://meshrcnn_R50.pth`

** fvcore version of PathManager will be deprecated soon. **
** Please migrate to the version in iopath repo. **
https://github.com/facebookresearch/iopath 

Traceback (most recent call last):
  File "./meshrcnn/demo/demo.py", line 19, in <module>
    import meshrcnn.data  # noqa
  File "/content/meshrcnn/meshrcnn/data/__init__.py", line 3, in <module>
    from . import datasets  # isort:skip
  File "/content/meshrcnn/meshrcnn/data/datasets/__init__.py", line 2, in <module>
    from .pix3d import load_pix3d_json  # isort:skip
  File "/content/meshrcnn/meshrcnn/data/datasets/pix3d.py", line 8, in <module>
    from detectron2.utils.file_io import PathManager
ModuleNotFoundError: No module named 'detectron2.utils.file_io'

**Comment by mkkiy** [comment]
I want to run a demo of mesh r-cnn on provided colab. I tried the same thing and had the same problem. It does not work with the following operations. Can you tell me what kind of operation should be added?

# install dependencies: (use cu101 because colab has CUDA 10.1) %env FORCE_CUDA=1 !pip install -U torch==1.5 torchvision==0.6 -f https://download.pytorch.org/whl/cu101/torch_stable.html !pip install pyyaml==5.1 pycocotools>=2.0.1 !pip install -U fvcore !pip install detectron2==0.1.3 -f https://dl.fbaipublicfiles.com/detectron2/wheels/cu101/torch1.5/index.html !pip install 'git+https://github.com/facebookresearch/pytorch3d.git'

Changes I tried

# install dependencies: (use cu101 because colab has CUDA 10.1)
%env FORCE_CUDA=1
!pip install -U torch==1.5 torchvision==0.6 -f https://download.pytorch.org/whl/cu101/torch_stable.html
!pip install pyyaml==5.1 pycocotools>=2.0.1
!pip install -U fvcore
!pip install detectron2==0.1.3 -f https://dl.fbaipublicfiles.com/detectron2/wheels/cu101/torch1.5/index.html

import os
!curl -LO https://github.com/NVIDIA/cub/archive/1.10.0.tar.gz
!tar xzf 1.10.0.tar.gz
os.environ["CUB_HOME"] = os.getcwd() + "/cub-1.10.0"
!pip install 'git+https://github.com/facebookresearch/pytorch3d.git@stable'

このコマンドも試しましたところインストールはできましたが，mesh r-cnnのdemoのブロックでエラーが起きました．下記に示します．

!python ./meshrcnn/demo/demo.py --config-file ./meshrcnn/configs/pix3d/meshrcnn_R50_FPN.yaml
--input /content/1.jpg --output output_demo --onlyhighest MODEL.WEIGHTS meshrcnn://meshrcnn_R50.pth

** fvcore version of PathManager will be deprecated soon. **
** Please migrate to the version in iopath repo. **
https://github.com/facebookresearch/iopath

Traceback (most recent call last):
File "./meshrcnn/demo/demo.py", line 19, in
import meshrcnn.data # noqa
File "/content/meshrcnn/meshrcnn/data/init.py", line 3, in
from . import datasets # isort:skip
File "/content/meshrcnn/meshrcnn/data/datasets/init.py", line 2, in
from .pix3d import load_pix3d_json # isort:skip
File "/content/meshrcnn/meshrcnn/data/datasets/pix3d.py", line 8, in
from detectron2.utils.file_io import PathManager
ModuleNotFoundError: No module named 'detectron2.utils.file_io'

**Comment by mkkiy** [comment]
I want to run a demo of mesh r-cnn on provided colab. I tried the same thing and had the same problem. It does not work with the following operations. Can you tell me what kind of operation should be added?

%env　FORCE_CUDA=1 
!pip install -U torch==1.5 torchvision==0.6 -f https://download.pytorch.org/whl/cu101/torch_stable.html
!pip install pyyaml==5.1 pycocotools>=2.0.1 
!pip install -U fvcore !pip install detectron2==0.1.3 -f https://dl.fbaipublicfiles.com/detectron2/wheels/cu101/torch1.5/index.html
!pip install 'git+https://github.com/facebookresearch/pytorch3d.git'

Changes I tried

%env FORCE_CUDA=1
!pip install -U torch==1.5 torchvision==0.6 -f https://download.pytorch.org/whl/cu101/torch_stable.html
!pip install pyyaml==5.1 pycocotools>=2.0.1
!pip install -U fvcore
!pip install detectron2==0.1.3 -f https://dl.fbaipublicfiles.com/detectron2/wheels/cu101/torch1.5/index.html
import os
!curl -LO https://github.com/NVIDIA/cub/archive/1.10.0.tar.gz
!tar xzf 1.10.0.tar.gz
os.environ["CUB_HOME"] = os.getcwd() + "/cub-1.10.0"
!pip install 'git+https://github.com/facebookresearch/pytorch3d.git@stable'

このコマンドも試しましたところインストールはできましたが，mesh r-cnnのdemoのブロックでエラーが起きました．下記に示します．

!python ./meshrcnn/demo/demo.py --config-file ./meshrcnn/configs/pix3d/meshrcnn_R50_FPN.yaml
--input /content/1.jpg --output output_demo --onlyhighest MODEL.WEIGHTS meshrcnn://meshrcnn_R50.pth

** fvcore version of PathManager will be deprecated soon. **
** Please migrate to the version in iopath repo. **
https://github.com/facebookresearch/iopath

Traceback (most recent call last):
File "./meshrcnn/demo/demo.py", line 19, in
import meshrcnn.data # noqa
File "/content/meshrcnn/meshrcnn/data/init.py", line 3, in
from . import datasets # isort:skip
File "/content/meshrcnn/meshrcnn/data/datasets/init.py", line 2, in
from .pix3d import load_pix3d_json # isort:skip
File "/content/meshrcnn/meshrcnn/data/datasets/pix3d.py", line 8, in
from detectron2.utils.file_io import PathManager
ModuleNotFoundError: No module named 'detectron2.utils.file_io'

**Comment by bottler** [comment]
@mkkiy (Your question is connected with https://github.com/facebookresearch/meshrcnn/issues/88 )

I think your question is actually meshrcnn specific. You haven't said how you installed meshrcnn, but it looks like you have an up-to-date version of it. meshrcnn is relying on recent changes in detectron2. `utils.file_io` is not in detectron2 0.1.3. You might be fine if you install the latest detectron2, version 0.3. Otherwise maybe you need to install detectron2 from github.

**Comment by mkkiy** [comment]
As advised, I updated Detection 2 to the latest version and it worked fine. Here's what worked. That was a really big help. Thank you.

%env FORCE_CUDA=1
!pip install -U torch==1.5 torchvision==0.6 -f https://download.pytorch.org/whl/cu101/torch_stable.html 
!pip install pyyaml==5.1 pycocotools>=2.0.1
!pip install -U fvcore
!pip install imgaug==0.2.6
!pip install 'git+https://github.com/facebookresearch/detectron2.git'
import os
!curl -LO https://github.com/NVIDIA/cub/archive/1.10.0.tar.gz
!tar xzf 1.10.0.tar.gz
os.environ["CUB_HOME"] = os.getcwd() + "/cub-1.10.0"
!pip install 'git+https://github.com/facebookresearch/pytorch3d.git@stable'
