### ISSUE TITLE
Memory usage of cubify

### ISSUE THREAD

**Issue by magicknight** [facebookresearch/pytorch3d#447]
## 🚀 Feature
Hi,
Thank you for sharing this great package.
Is it possible to make cubify to work on a large 3D array? I found that on my 64 GB workstation it crashed when processing an array larger than 500x500x500. 
I am not sure how to do this, maybe by segmentation?

## Motivation

To use cubify on large data

## Pitch

I think a lot of 3D voxel files are larger than a few hundreds per side

**Comment by gkioxari** [comment]
Cubify, marching cubes etc. are rather complex operations and achieving a desirable trade off between speed and memory is key. In PyTorch3D we tuned the implementation for the following use case in mind: A batch size (:= 32 - 64) of medium sized voxels (:= 64^3). The vectorized implementation in PyTorch3D was the most efficient in terms of memory and speed for that use case. 

Your use case is rather different since your voxels are big and the vectorized implementation which unavoidably makes use of memory to achieve it is likely not the best strategy. A coarse-to-fine approach might work best e.g. breaking the big voxel into smaller medium sized voxels.
