### ISSUE TITLE
Why the rendered depth image is not complete?

### ISSUE THREAD

**Issue by kalyo-zjl** [facebookresearch/pytorch3d#448]
Hi, @gkioxari 
I have a face obj file which can be correctly viewed in Meshlab. 
![1](https://user-images.githubusercontent.com/19725489/99146421-00d6a300-26b3-11eb-9202-39a054798e81.png)
However, when rendering with pytorch3d, the result is not as expected. The following is the depth image
![2](https://user-images.githubusercontent.com/19725489/99146469-70e52900-26b3-11eb-9f02-ea63dce295c1.png)

The code and the obj file to reproduce the result is in the following. Can you tell me how to solve it?

[0.zip](https://github.com/facebookresearch/pytorch3d/files/5540643/0.zip) # obj file

```python
import torch
from pytorch3d.structures import Meshes
from pytorch3d.io import load_obj

from pytorch3d.renderer import (
  RasterizationSettings,
  MeshRasterizer,
  SfMPerspectiveCameras,
)
import matplotlib.pyplot as plt

image_size = 640 # 512
raster_settings = RasterizationSettings(
      image_size=image_size,
      blur_radius=0,
      faces_per_pixel=1,
    )
ptR = [[[-1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]]
ptR = torch.FloatTensor(ptR)
cameras = SfMPerspectiveCameras(focal_length=1015. * 2 / image_size,
                                R=ptR.expand(1, -1, -1),
                                device='cuda')
rasterizer = MeshRasterizer(raster_settings=raster_settings)

obj = load_obj('0.obj')
v = obj[0]
v[..., -1] *= -1
mesh = Meshes(verts=[v], faces=[obj[1].verts_idx]).cuda()
fragments = rasterizer(mesh, cameras=cameras)

zbuf =fragments.zbuf
plt.imshow(zbuf[0, ..., 0].cpu().numpy())
plt.show()
```

**Comment by gkioxari** [comment]
You need to set `max_faces_per_bin` in the rasterization settings. Here is what the output looks like, if you set `max_faces_per_bin=20000`

![0](https://user-images.githubusercontent.com/4369065/99196664-ac7b0400-2742-11eb-826e-ca004f3106c6.png)

```python

device = torch.device("cuda:1")

obj_filename = "/tmp/output/0.obj"
verts, faces, aux = load_obj(obj_filename, device=device, load_textures=False)

# Convert to PyTorch3D world system
# (+X left, +Y up, +Z in)
R_to_py3d = torch.tensor(
    [[-1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, -1.0]],
    dtype=torch.float32,
    device=device,
)
verts = torch.mm(verts, R_to_py3d)

# add white color vertex texture
tex = TexturesVertex(
    torch.ones((1, verts.shape[0], 3), device=device, dtype=torch.float32)
)
mesh = Meshes(verts=[verts], faces=[faces.verts_idx], textures=tex)

image_size = 512
cameras = PerspectiveCameras(focal_length=1015.0 * 2.0 / image_size, device=device)
raster_settings = RasterizationSettings(
    image_size=image_size, blur_radius=0, faces_per_pixel=1, max_faces_per_bin=20000
)
renderer = MeshRenderer(
    rasterizer=MeshRasterizer(cameras=cameras, raster_settings=raster_settings),
    shader=HardGouraudShader(device=device, cameras=cameras),
)
image = renderer(mesh)

filename = "/tmp/output/0.png"
rgb = image[0, ..., :3].detach().squeeze().cpu()
Image.fromarray((rgb.detach().cpu().numpy() * 255).astype(np.uint8)).save(filename)
```

## A brief explanation of our coarse-to-fine rasterization

Our rendering engine takes a coarse to fine approach which breaks the image into tiles. Each tile computes its outputs by allocating a fixed size memory defined by `max_faces_per_bin` in the rasterization settings. If this value is not set, we define it based on some heuristics. The heuristic work well especially when the mesh occupies the image rather uniformly. However, in your case, your mesh is large-ish and far from the camera meaning that it occupies a small part of the image. Since you are not defining `max_faces_per_bin` the heuristic fails to allocate enough memory. The same issue is explained in https://github.com/facebookresearch/pytorch3d/issues/348 and https://github.com/facebookresearch/pytorch3d/issues/316

**Comment by kalyo-zjl** [comment]
Got it, thanks so much! @gkioxari
