### ISSUE TITLE
Installation issues.

### ISSUE THREAD

**Issue by shersoni610** [facebookresearch/pytorch3d#47]
Hello,

Sorry, I am a newbee to Pytorch but got attracted to 3D mesh.  I am having very hard time 
making Pytorch3D working. I am not sure if I should be asking these questions here.

1.   I installed NVidia-Driver 440.59 on Ubuntu 18.04. 
2.   The Compiler is GCC 8.3
3.   nvidia-smi says that CUDA-10.2 is installed. 
4.   Thereafter, I went to Pytorch library and opted Conda + 10.1 with the given command:
      conda install pytorch torchvision cudatoolkit=10.1 -c pytorch

      Even after 5 hours the above command did not do anything. So I gave it up.

5.   I installed pytorch from conda command i.e. pytorch-gpu. 
6.   All simple examples worked. No issues moving data from CPU-GPU and back.
7.   I installed Pytorch3D. No example worked. For example:

(base) :$ python test_utils.py 
Traceback (most recent call last):
  File "test_utils.py", line 8, in <module>
    from pytorch3d.renderer.utils import TensorProperties
  File "/home/Disk/Software/Anaconda3/lib/python3.7/site-packages/pytorch3d/renderer/__init__.py", line 19, in <module>
    from .mesh import (
  File "/home/Disk/Software/Anaconda3/lib/python3.7/site-packages/pytorch3d/renderer/mesh/__init__.py", line 3, in <module>
    from .rasterize_meshes import rasterize_meshes
  File "/home/Disk/Software/Anaconda3/lib/python3.7/site-packages/pytorch3d/renderer/mesh/rasterize_meshes.py", line 9, in <module>
    from pytorch3d import _C
ImportError: /home/Disk/Software/Anaconda3/lib/python3.7/site-packages/pytorch3d/_C.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceIN3c108BFloat16EEEPKNS_6detail12TypeMetaDataEv

How to resolve these issues? It seems that the problem may be with Pytorch, Cuda, and NVidia Drivers. Installing all these libraries turned out to be a nightmare. 

Can someone write how to correctly installed these libraries so that Pytorch3D work as expected.

Thanks

**Comment by bottler** [comment]
The problem to solve is number 4. That is the correct thing to run and should run easily. 

`conda install pytorch-gpu`, which I think is what you did in 5, won't help. I don't know where that package comes from, but it is an older version (1.3) of pytorch. Pytorch3d won't work with that.

Can you set up a new conda environment with python working?  E.g. `conda create -n myenv python=3.8`. If this doesn't work then conda isn't working. If it is, then it would be interesting to see what happens if you do `conda activate myenv`, `conda list` and then `conda install pytorch torchvision cudatoolkit=10.1 -c pytorch`

**Comment by nikhilaravi** [comment]
@shersoni610 were you able to resolve this installation issue? If so, please close this issue. Thank you!

**Comment by nikhilaravi** [comment]
Closing this issue! If you are still having problems feel free to reopen it.
