### ISSUE TITLE
Runtime error in "cubify"

### ISSUE THREAD

**Issue by AstitvaSri** [facebookresearch/pytorch3d#513]
I'm getting following runtime error while running "pytorch3d.ops.cubify":

**/usr/local/lib/python3.6/dist-packages/pytorch3d/ops/cubify.py in cubify(voxels, thresh, device, align)
    223     idleverts = torch.ones(num_verts * N, dtype=torch.uint8, device=device)
    224 
--> 225     idleverts.scatter_(0, grid_faces.flatten(), 0)
    226     grid_faces -= nyxz[:, 0].view(-1, 1) * num_verts
    227     split_size = torch.bincount(nyxz[:, 0], minlength=N)**

**RuntimeError: Expected index [887112] to be smaller than self [256496] apart from dimension 0 and to be a smaller size than src [256496]**

The input voxel tensor is of size [1, 40, 45, 135] which consists of occupancy probabilities as either 0 or 1.
I'm not able to understand the error. What is the cause of this issue?

**Comment by gkioxari** [comment]
Could you please provide the data as well as a compact code snippet for us to reproduce the error?

**Comment by AstitvaSri** [comment]
Download **.npy** files from here : https://drive.google.com/drive/folders/1TrlXsTizN98qWN9vw1rWP45esSZVcWpV?usp=sharing

```
import pytorch3d
import torch
from pytorch3d.ops import cubify
import numpy as np

voxel = np.load('voxel.npy')
print("Voxel Contents:",np.unique(voxel))
print("Occupied blocks:",np.count_nonzero(voxel))

voxel = torch.FloatTensor(voxel)
voxel = voxel.unsqueeze(0)
print("Voxel Dimensions:",voxel.size())

mesh = cubify(voxel,0.5)
```
Is there something wrong with the voxel data?

**Comment by gkioxari** [comment]
I had no issue running cubify on your voxel. Here is a snippet of code to get the result

```python 
device = torch.device("cuda:1")
data = np.load("/tmp/output/voxel.npy")
voxels = torch.from_numpy(data).to(dtype=torch.float32, device=device)
voxels = voxels.unsqueeze(0)
mesh = cubify(voxels, 0.5)
filename = os.path.join("/tmp/output/voxel_mesh.obj")
save_obj(filename, mesh.verts_list()[0], mesh.faces_list()[0])
```
and here is the output 
[voxel_mesh.obj.zip](https://github.com/facebookresearch/pytorch3d/files/5794116/voxel_mesh.obj.zip)

**Comment by sibowi** [comment]
I get the same error, and I'm very confused about what it means and why it is caused. I entered a few different cases below. Can you help me understand what goes wrong?

`volume = torch.zeros((1, 2, 3, 8))

case = 'A'

if case == 'A':
    # Should result in a single mesh at the edge of the volume -> No error
    volume[:, 0, 0, -1:] = 1
if case == 'B':
    # Should result in a single mesh at the edge of the volume -> Error
    volume[:, 0, 0, 3:] = 1
elif case == 'C':
    # Should result in two independent meshes at different edges of the volume 
    # -> No error when dim=3 is 8
    # -> Error when dim=3 is 4
    volume[:, 0, 0, -1:] = 1
    volume[:, 0, 0, :1] = 1
elif case == 'D':
    # Should result in two independent meshes not touching the edges of the volume -> No error
    volume[:, 0, 0, 1:2] = 1
    volume[:, 0, 0, 5:6] = 1

mesh = pytorch3d.ops.cubify(volume, thresh=1., align='corner')`

The error looks like this:
`---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-50-496c18b5bbe6> in <module>
     20     volume[:, 0, 0, 5:6] = 1
     21 
---> 22 mesh = pytorch3d.ops.cubify(volume, thresh=1., align='corner')
     23 
     24 mesh.verts_list(), mesh.faces_list()

~/.conda/envs/mesh_utils/lib/python3.8/site-packages/torch/autograd/grad_mode.py in decorate_context(*args, **kwargs)
     24         def decorate_context(*args, **kwargs):
     25             with self.__class__():
---> 26                 return func(*args, **kwargs)
     27         return cast(F, decorate_context)
     28 

~/.conda/envs/mesh_utils/lib/python3.8/site-packages/pytorch3d/ops/cubify.py in cubify(voxels, thresh, device, align)
    223     idleverts = torch.ones(num_verts * N, dtype=torch.uint8, device=device)
    224 
--> 225     idleverts.scatter_(0, grid_faces.flatten(), 0)
    226     grid_faces -= nyxz[:, 0].view(-1, 1) * num_verts
    227     split_size = torch.bincount(nyxz[:, 0], minlength=N)

RuntimeError: Expected index [132] to be smaller than self [108] apart from dimension 0 and to be smaller size than src [108]`

**Comment by patmjen** [comment]
It seems like the issue comes from `grid_faces.flatten()` having more elements than `idleverts` (here `idleverts` has 108 and `grid_faces` has 132). However, `grid_faces` has a lot of repeated elements. Changing line 225 to call unique on `grid_faces` like so:
```
idleverts.scatter_(0, grid_faces.unique().flatten(), 0)
```
seems to fix it - at least for the test cases provided by @sibowi.

**Comment by patmjen** [comment]
Looking into it a bit more, I also recreated the original issue by @AstitvaSri. Running the provided code gives the same error. @gkioxari it looks like the reason you did not get an error is that you first place the input on the GPU - this is *not* done in the examples by @AstitvaSri or @sibowi.

The CUDA version of `scatter_` does not give an error if the `index` argument is too long, but the CPU version does. Instead, the CUDA version seems to just handle the extra entries correctly, as shown in the below example:
```python
device = torch.device('cuda')  # This will work fine
# device = torch.device('cpu')  # This will give an error
x = torch.arange(10, device=device)
idx1 = torch.tensor([4, 2, 0, 8, 0, 1], device=device)
idx2 = torch.tensor([4, 2, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], device=device)  # Too long for CPU

print('idx1.numel() =', idx1.numel())
print(x.scatter_(0, idx1, 0))
# idx1.numel() = 6
# tensor([0, 0, 0, 3, 0, 5, 6, 7, 0, 9], device='cuda:0')

print('idx2.numel() =', idx2.numel())
print(x.scatter_(0, idx2, 0))
# idx2.numel() = 14
# tensor([0, 0, 0, 3, 0, 5, 6, 7, 0, 9], device='cuda:0')
```
The fix in my previous comment (calling `unique`) seems to give the same mesh as if run on the GPU for @AstitvaSri's example. I think it would fix the issue since if you only keep unique vertex indices it would not be possible to have more entries than vertices. But maybe I'm missing some extra context. I guess ideally, you'd want `scatter_` to just always behave like the CUDA version, so we wouldn't have to care, but then it would be a PyTorch issue.

**Comment by gkioxari** [comment]
@patmjen thanks a lot for the great detective work!  I think this is a PyTorch issue. The CPU and CUDA version of a PyTorch op should behave the same. Could you open a PyTorch issue to flag this so that they fix it? In the mean time, I will look into cubify and see if adding `.unique()` creates issues.

**Comment by patmjen** [comment]
@gkioxari sounds great, thank you! I'll open an issue on PyTorch in the next few days which will also refer back to this issue.
