### ISSUE TITLE
Mesh -> Mesh DNN with pytorch3D

### ISSUE THREAD

**Issue by weizmanl** [facebookresearch/pytorch3d#515]
Hi,

My task is build a DNN that inputs a mesh and outputs a mesh. I'd like to do it with convolution, relu and maxpooling operators on meshes (a Unet style).

1. Is it possible with pytorch3D?
2. pytorch3d has GraphConv (which I believe is the equivalent of convolution for meshes), but how do I specify the kernel size? 
3. Is there any equitant for maxpooling on meshes in pytorch3d?

If you have an example for a mesh->mesh network that would be great!

Thank you

**Comment by gkioxari** [comment]
Your question is not pertinent to an issue with PyTorch3D. Though I will respond with some reference points

> 1. Is it possible with pytorch3D?

Yes, it is. 

> 2. Graph Conv

You should read through the implementation of graph conv so that you understand what it does and what it computes. Graph Conv applies MLPs on nodes and sums the output across edges in the mesh graph. 

> 3. Maxpooling in meshes

In the case of meshes, features are associated to nodes in the graph. So maxpooling across features in neighboring nodes would be a maxpooling operation that you could perform. But I don't know what exactly you want. 

From your message, it seems like you just want to do a plug-and-play of a CNN to a mesh (i.e. a graph). This is not the right way of thinking about things. You should define what operations you want to perform on a graph and then think about how to implement them on a graph.

**Comment by densechen** [comment]
@weizmanl Did you build such U-Net? Can you share it with me.
