### ISSUE TITLE
quaternion_to_matrix returns row major matrix instead of column major matrix

### ISSUE THREAD

**Issue by Relento** [facebookresearch/pytorch3d#582]
https://github.com/facebookresearch/pytorch3d/blob/4bb3fff52b7e26ec0f013021cb26fab7db3d8e0b/pytorch3d/transforms/rotation_conversions.py#L50-L63

![image](https://user-images.githubusercontent.com/23029424/109775489-6d1fd880-7bb6-11eb-895b-753fd8bf55ff.png)

According to the conversion formula, I think current implementation of quaternion_to_matrix returns the matrix that applies to row vectors rather than column vectors. This is inconsistent with the documentation.

**Comment by bottler** [comment]
If you look at [this test](https://github.com/facebookresearch/pytorch3d/blob/master/tests/test_rotation_conversions.py#L192), which passes, you will see that given a point `p` and a quaternion `q`, `quaternion_apply(q,p)` does the same thing as premultiplying the (`p` converted to column matrix) by `quaternion_to_matrix(q)`. This seems to be exactly what you want to be true.

The code of ours which you quote and the image you pasted look like they agree, because the layout of torch tensors (which the `reshape` in our code uses) is in row-major order.

**Comment by Relento** [comment]
Thanks for your prompt reply! I just realized that transform3d.py and rotation_conversions.py have different transform matrix conventions and it's intended that quaternion_to_matrix returns the matrix that applies to row vectors rather than column vectors.
