### ISSUE TITLE
Speed of rendering

### ISSUE THREAD

**Issue by Yumin-Sun-00** [facebookresearch/pytorch3d#591]
## ❓ How is the speed to render a mesh, could we have a performance table to compare?

To render a mesh with 25k vertices of image width-height-channel 4096x4096x4. And I use GPU. My shader only uses the fragments from rasterizer to render a most simple image, without anymore complex operations like lightning or blending.

With python `time `module, I use roughly 5.6 seconds.

I think this is not what I expected. How is the speed to render a most simple image with 25k vertices and the same image resolution as I have?

My raster settings
`raster_settings = RasterizationSettings(image_size=args.width,bin_size=0, blur_radius=0, faces_per_pixel=1)`

My shader:

```
class Shader(nn.Module):
    def __init__(self, device):
          super().__init__()
          self.device = device
    def to(self,device):
         pass
         return
    def forward(self, fragments, meshes):
        texels = meshes.sample_textures(fragments) # call interpolate_face_attribute()
        tensor_images = texels[...,0,:]
        return tensor_images
```

**Comment by nikhilaravi** [comment]
@Yumin-Sun-00 when you set `bin_size=0` this uses the "naive" rasterization kernel instead of the more optimized "coarse-to-fine" kernel which can be used by setting `bin_size=None` (bin_size is heuristically set based on the mesh size). 

https://github.com/facebookresearch/pytorch3d/blob/4bb3fff52b7e26ec0f013021cb26fab7db3d8e0b/pytorch3d/renderer/mesh/rasterize_meshes.py#L68-L71

**Comment by nikhilaravi** [comment]
Great!
