### ISSUE TITLE
The behavior the source mesh is Not one mesh.

### ISSUE THREAD

**Issue by tsudamasaki** [facebookresearch/pytorch3d#630]
I have a question about the behavior when the source mesh isn't primitive shape.

The tutorial use one mesh for target and source file.

I tried to use my own obj file that is consisted of some parts.
Although the shape in step seems to be deformed, but the final object file is not similar   to the target file.
I'd like to know whether I should not use obj that is consisted  from multi parts.

**Comment by gkioxari** [comment]
You don't provide enough information for us to be able to help you. 

Code and data so that we can reproduce your problem would be necessary. However, since this is not an issue with the library but it seems to be a question about how to use PyTorch3D, I would recommend using the discussions feature of Github. Thank you :)
