### ISSUE TITLE
Could Pulsar renderer return fragments?

### ISSUE THREAD

**Issue by bobiblazeski** [facebookresearch/pytorch3d#653]
## ❓ Questions on how to use PyTorch3D

I'm trying to use pytorch3d points renderer with my own compositor 

```
fragments = self.renderer.rasterizer(point_clouds, **kwargs)
images = self.custom_compositor(fragments, point_clouds) 
```

Is there a way for pulsar renderer to return the fragments if that makes sense?
As much as I could understand pulsar is using passed rasterizer just to extract information.
```
class PointFragments(NamedTuple):
    idx: torch.Tensor
    zbuf: torch.Tensor
    dists: torch.Tensor
```

**Comment by classner** [comment]
Hi @bobiblazeski!

Indeed, the pulsar backend only uses the objects from PyTorch3D to "extract" the configuration, and then has most of the rendering steps merged in CUDA kernels for the highest possible efficiency. So the short answer is: no, they're not accessible.

However, there is a longer answer. You might still be able to extract the information that you're looking for, at least partially. Pulsar *does* store some of this information in an additional buffer for the backward pass. Concretely, only for the spheres which are involved in the gradient calculation (usually the closest five to the camera for every pixel; this is configurable with the parameter `n_track` that can be passed when constructing the renderer) the sphere IDs can be extracted, as well as the intersection depth. For that, you can request this additional buffer by specifying `return_forward_info=True` to the forward function. Then, the forward function returns two values: the image, and this additional buffer object.

The buffer object has the same width and height as the image, and in the channels [4::2] the intersection depths. The renderer has the function `sphere_ids_from_result_info_nograd` which takes the result_info buffer and gives you the sphere IDs (there's some type cast magic going on in the background so it's the easiest way to use that method to do it efficiently).

Currently, all of this only works with the direct pulsar interface, not with the unified PyTorch3D interface. Let me know if you have any further questions!

**Comment by zydmu123** [comment]
Hello, @classner !

**Comment by zydmu123** [comment]
Hello, @classner !

**Comment by zydmu123** [comment]
Hello, @classner !
I am a beginner with the pulsar render and I'm a little confused about your above answer:
"The buffer object has the same width and height as the image, and in the channels [4::2] the intersection depths."

While in the function description，it says: 
" The following channels alternate with the float encoded integer index of a sphere and its weight. They are the five spheres with the highest color contribution to this pixel color, ordered descending. Default: False."

 Shouldn't the channels [4::2] be "weight" instead of "depths"? However, the value of those channels are obvious "depths"..
Did I misunderstand something very important? I'd also like to konw how to get the "weight" of the spheres.
I'd really appreciate it if you could answer these questions. Many thanks for you!

**Comment by classner** [comment]
Hi @zydmu123 ,

Great question! You can find the code that takes care of this right here: https://github.com/facebookresearch/pytorch3d/blob/main/pytorch3d/csrc/pulsar/include/renderer.render.device.h#L397-L401 . In short: it's the sphere depth, and that is directly used to determine the blend weight (see the paper Eq. 1). Given the exact intersection depth of ray and sphere, determining the blending factor is very fast and simple. But to your point, the function description should be adjusted to say that it is the depth.
