### ISSUE TITLE
RuntimeError: Must have num_closest <= 150  limits for faces per pixels. 

### ISSUE THREAD

**Issue by gaetan-landreau** [facebookresearch/pytorch3d#679]
## ❓ Is there a limit onto the number of faces per pixels during rasterisation ? 

I'm trying to overwrite the **forward()** method from _MeshRenderer_ class in order to output both the rendered images and the intermediate Fragments tensors. However, when I set in the rasterizer the `faces_per_pixel` to a number higher than 150 (for instance by setting this parameter to the total number of faces in the mesh) I've this RuntimeError. 

From what I've understood, this parameter allow to explicitly clip the number of faces used in the shader for instance (for the silhouette aggregation step for instance). There is thus no way to get the Fragment tensors __dists__ with size  (N, H, W, K) where K=tot_nb_faces ? 

Thanks a lot ! :)

**Comment by nikhilaravi** [comment]
Yes there is a limit which is [set here](https://github.com/facebookresearch/pytorch3d/blob/master/pytorch3d/csrc/rasterize_meshes/rasterize_meshes.cu#L1006-L1008) as otherwise you will run out of CUDA memory. Remember that the output tensors from rasterization are of shape `(N, H, W, K)` so for very large K you will require a large amount of memory.  

Here's an explanation of how the memory usage is calculated: https://github.com/facebookresearch/pytorch3d/blob/master/docs/notes/renderer.md#get-started 

What is your use case for which you require K= tot_nb_faces?

**Comment by gaetan-landreau** [comment]
Thanks a lot for your answers ! 
This was mainly for my own personal comprehension of the PyTorch3D and SoftRasterizer rasterizer, since I know that in SoftRasterizer all the faces are involved during the aggregation. To the best of my knowledge, in the SoftRasterize CUDA kernel code, one of the main loop is made over all the faces of the mesh, there is no Z-buffer tests made and we can theoretically pop out all the same __dist__ fragments tensors for all the faces. 

Thanks a lot for your help !

**Comment by nikhilaravi** [comment]
@gaetan-landreau in SoftRasterizer they don't save all the intermediate values for dists per face and only keep one aggregated value per pixel.
