### ISSUE TITLE
White patches in rendered images

### ISSUE THREAD

**Issue by pangyyyyy** [facebookresearch/pytorch3d#692]
## 🐛 Bugs / Unexpected behaviors
Rendered images contain white/ glitchy patches at lower image resolutions.

## Instructions To Reproduce the Issue:
I generated renderings for ShapeNet .obj models following `fit_textured_mesh` tutorial and realised that many of my rendered images contain artifacts (see pic1) - white random patches.  

![pic1](https://user-images.githubusercontent.com/46132074/120111236-becf0380-c1a3-11eb-876a-2daeba6bb213.JPG)

This is the mesh obj viewed in Meshlab. 
![pic2](https://user-images.githubusercontent.com/46132074/120111248-c7bfd500-c1a3-11eb-9b1e-23c5669c3901.JPG)

This problem persist after changing different camera settings and camera type. 

This was the original setting:
```
raster_settings = RasterizationSettings(
    image_size=128,  
    blur_radius=0.0, 
    faces_per_pixel=1, 
    perspective_correct=False
)
```
The only "fix" I found was to increase the `image_size` parameter from 128 to >400 for this particular model (pic3 is the output after changing the resolution). 

![pic3](https://user-images.githubusercontent.com/46132074/120111252-cd1d1f80-c1a3-11eb-8b6b-053141a6c1f0.JPG)

I was wondering if there is an explanation for why these glitchy patches occur? and if there's a way to render images normally at low resolutions?

**Comment by bottler** [comment]
I think this might be happening because of an overflow in statically allocated bins in the coarse-to-fine rasterization; it's a known phenomenon. The explanation would be the same as #348. You can try to fix it by setting `max_faces_per_bin` in the RasterizationSettings to something large - e.g. something nearly as large as the number of faces in the mesh. Alternatively you can use the naive rasterizer, by adding bin_size=0 to the RasterizationSettings, but that is likely to be slower.

**Comment by pangyyyyy** [comment]
The explanation in the provided link #348 was really helpful and thank you so much for swiftly providing a solution!!- changing the `max_faces_per_bin` works for me
