### ISSUE TITLE
Add torch as a requirement into setup.py

### ISSUE THREAD

**Issue by oleks-popovych** [facebookresearch/pytorch3d#701]
## 🚀 Feature

Add `torch` as a requirement to setup.py, in order to install it first, before compiling a package.

## Motivation

Right know in order to add `pytorch3d` as a dependency I need to make a few tricks, to make sure `torch` is installed first. 
I'd like to have it installed along with `pytorch3d`, not separatelly.

## Pitch

This enhancement will help to install `pytorch3d` into completely new environment from scratch. This will require less effort from users to deliver their code into production

**Comment by bottler** [comment]
Not doing this is mostly a feature, not a bug. We need the user to be deliberate about which torch they install. We need to force the user to think for themselves about which PyTorch they install into the environment. This includes which version of CUDA, if any, will they work with in this environment. 

If you are installing PyTorch3D from source with pip, then we don't want to stop you using a newer version of PyTorch than the ones which were current at the time of the commit you are working on (e.g. stable, the last release). However we can't see into the future so we can't promise this will work, so we wouldn't want pip to default to downloading the latest version of torch. These two considerations mean that listing pytorch as a dependency with or without an allowed range of versions would be problematic. 

Our recommended installation of prebuilt packages on linux is with conda. Here the dependency on PyTorch is encoded in the package, but PyTorch still needs to be manually installed. This is not due to setup.py.

The wheels we provide for linux are mainly designed to make life easy for users of Google Colab, who already have PyTorch installed. So encoding the dependency there is not important.

The last case is the wheels on PyPI for mac, where only one PyTorch version is supported and CUDA is not supported. Here you have a good suggestion. In this specific case I agree it would be useful if they could encode the particular PyTorch version they depend on. This is a more complicated change to the build than something in setup.py, and probably would need to be done by us, unless you can see how to make it happen.
