### ISSUE TITLE
Exception when creating a TextureAtlas

### ISSUE THREAD

**Issue by iAhmedMaher** [facebookresearch/pytorch3d#751]
Hello,

When I try to load a multi-textured object using the instructions [here](https://github.com/facebookresearch/pytorch3d/issues/493), an exception is thrown while loading with these messages as seen in the attached image below:

![image](https://user-images.githubusercontent.com/9035150/124989618-973f4680-e03f-11eb-9914-a57e0bd3acf7.png)

I tried to look into the mtl_io.py file and found that some values of x1 are out of the image's range by 1. Setting those to the max possible index loads and renders the image correctly for a human, but I don't know if some faces have wrong textures or not especially that I don't fully understand uv texturing in general. I checked how x1 gets its values and it seems weird to me that it is [x0 + 1](https://github.com/facebookresearch/pytorch3d/blob/44d2a9b623d7559e98688afb1c4c99aa620b1873/pytorch3d/io/mtl_io.py#L342) while x0 have values (H - 1) as seen below:
![image](https://user-images.githubusercontent.com/9035150/124990339-83e0ab00-e040-11eb-80a1-588a1730db61.png)

### Environment 
I am using the environment setup in [one of the tutorial notebooks](https://pytorch3d.org/tutorials/render_textured_meshes), so the latest stable version of Pytorch3D as of the time of writing this issue. 

I am using Google Colab, so it's on Linux. 

The issue is present when using a GPU. When using a CPU instead, the notebook crashes.

The texture images have size of 4096x4096. I am not authorized to share them or the obj files, sorry.

**Comment by iAhmedMaher** [comment]
@nikhilaravi Here is my code snippet. This is the same snippet shared [here](https://github.com/facebookresearch/pytorch3d/issues/493). I have tried all texture_wrap options and texture_atlas_size sizes, but none of them worked.

verts, faces, aux = load_obj(
                            obj_filename,
                            device=device,
                            load_textures=True,
                            create_texture_atlas=True,
                            texture_atlas_size=8,
                            texture_wrap=None
                            )
atlas = aux.texture_atlas

mesh = Meshes(
            verts=[verts],
            faces=[faces.verts_idx],
            textures=TexturesAtlas(atlas=[atlas]),
            )

**Comment by nikhilaravi** [comment]
@iAhmedMaher the device side assert is due to the UV values being out of bounds for the image during indexing. We can't use grid sample and bilinear interpolation because the texture atlas type is not continuous in the U and V directions - see this comment for an explanation of how the texture atlas is created during loading of the object: 

https://github.com/facebookresearch/pytorch3d/blob/6c416b319c6990ba1beeb2bf1988b96acfa31618/pytorch3d/io/mtl_io.py#L144-L184 

We have to convert the UV coordinates to integers in order to index into the texture map. `x0, x0+1, y0, y0+1` are the indices of the neighbors for each of the interpolation points however this doesn't properly handle the out of bound values in the same way as the `grid_sample` function does with the `padding_mode` argument. 

Can you try replacing this line with `_bilinear_interpolation_grid_sample`?: 

https://github.com/facebookresearch/pytorch3d/blob/44d2a9b623d7559e98688afb1c4c99aa620b1873/pytorch3d/io/mtl_io.py#L302 

If this works I will update the original implementation to use this grid sample version.

**Comment by nikhilaravi** [comment]
@iAhmedMaher great!! I will update the original implementation!

**Comment by nikhilaravi** [comment]
This has been fixed in https://github.com/facebookresearch/pytorch3d/commit/fc156b50c0d6147ca00755059fb1ff96133827df.
