### ISSUE TITLE
Another instance of empty images (pulsar)

### ISSUE THREAD

**Issue by saulzar** [facebookresearch/pytorch3d#755]
I'm also seeing the issue reported in #543 ... two machines, one works one doesn't both Ubuntu 20.04 both RTX 2070 GPU, pytorch3d built from source (as of yesterday) with fa44a05

cuda 11.3 pytorch 1.8.1 - empty image
cuda 11.4 pytorch 1.6 - works fine

**Comment by saulzar** [comment]
I see that pytorch 1.8 isn't supported yet, that is probably why, will test this first.

**Comment by bottler** [comment]
If you build PyTorch3D from source, it should be fine with PyTorch 1.8.1 and 1.9.0. I haven't tested with CUDA newer than 11.1 though (which is the newest which PyTorch has builds for). The typical cause of this problem is certain versions of CUB which don't seem to work at all. CUB is now bundled with CUDA, so it is easy to lose control over the version of CUB you are using. Setting CUB_HOME to the one you've downloaded should override the default one.

**Comment by saulzar** [comment]
I downgraded to 1.7.1 and I no longer had empty images, I will try with the CUB_HOME setting. Thanks.
