### ISSUE TITLE
How to save rendered images as png or jpg files?

### ISSUE THREAD

**Issue by bhowmickarka** [facebookresearch/pytorch3d#844]
Hello,
I have a very simple question. After rendering  a mesh using the **SoftPhongShader** , I want to save the rendered image as png files, but when I do that  it is always black. And when  I print the channel values  it is always 1. So, it will be really helpful if someone can tell me how can I save the rendered images. 
I know it might be a stupid question to ask, but there is one more thing that I do not understand is that, when we visualize the images in the notebook it works, and that is weird because when I print the channel values, it is always 1. So, a little guidance will be really helpful.
Thank you

**Comment by bottler** [comment]
There's nothing special about a notebook. If you visualize an image (e.g. with matplotlib) which is entirely ones you won't see anything interesting (just a single color). 

I can think of two possible gotchas with saving images:

1) The output of the SoftPhongShader has a fourth channel, indicating the probability that the pixel hits a face. Instead of visualizing/saving an RGB image, you might be saving an RGBA image including this channel. Different image viewers may do different things when viewing an image containing a fourth ("alpha") channel. It might be helpful to save and visualise just RGB, i.e. start by just using `images[..., :3]`.

2) It is possible to set up lighting in such a way that the output of the renderer contains values above 1.0, perhaps only by a tiny amount. This might confuse libraries which save or visualise images, in inconsistent ways. For example, they might think the values are in [0,255] instead of [0,1] and make everything black. Reducing the lighting slightly might help.

**Comment by bhowmickarka** [comment]
Thank you for your reply. I was able to save the rendered images by converting the tensor to numpy and then multiplying with 255. 
I will close this issue.
