### ISSUE TITLE
 Could I use the cuda 9.0 to use Pytorch3d normally? 

### ISSUE THREAD

**Issue by liyouhua123** [facebookresearch/pytorch3d#88]

**Comment by bottler** [comment]
I don't know, but you would have to build a lot of things manually. There are no prebuilt conda packages for pytorch or torchvision or pytorch3d for that version of CUDA. Building all these from scratch may not be so simple.

If your real question is, "I have Cuda 9.0 installed, is it easy for me to use pytorch3d?" then there are alternatives. 
* If you are using conda, you can create a new environment and install a newer cudatoolkit package in there. This is how we recommend installing. Then it doesn't matter what version of cuda you have installed on the machine, pytorch3d can use the newer one in the environment. The presence of conda on your machine is irrelevant to pytorch3d. (However, for this to work easily, you must have a new enough GPU and the drivers must be installed and new enough.)
* If you want to just experiment with pytorch3d, you can consider using colab instead of your machine.
* If you want to experiment with pytorch3d on your machine, you can just stick to the CPU. I think it will be best to install from source straight from github.
