### ISSUE TITLE
Artifacts when fitting the texture map visible in MeshLab and Blender but not in PyTorch3D

### ISSUE THREAD

**Issue by simon-cross** [facebookresearch/pytorch3d#943]
I have taken the PyTorch3D tutorial ["Fit a mesh via rendering"](https://pytorch3d.org/tutorials/fit_textured_mesh) and instead of fitting the mesh and the colors per vertex, I have taken the ground truth input mesh and I have fitted only its texture map that I have initialized to a uniform black image.

When I render the mesh and the fitted texture map with the renderer of PyTorch3D everything looks good, but when I use MeshLab or Blender to render the fitted texture map, I see artifacts located at the borders of the different colored regions in the texture map. 

This is a rendering of the mesh with the fitted texture map in MeshLab with the artifacts shown by the red arrows:
![Screenshot from 2021-11-18 23-02-01](https://user-images.githubusercontent.com/92995595/142513945-62bbd429-4e3a-42f5-b4c6-6bcdf9612684.png)

This is a rendering of the mesh with the fitted texture map in PyTorch3D (parameters specified below):
![image_cam160](https://user-images.githubusercontent.com/92995595/142513979-af57f967-af5d-4321-9b03-03b438b7cbb7.png)

This is the fitted texture map:
![cow_texture](https://user-images.githubusercontent.com/92995595/142513996-f0952fbe-f0be-49d4-8868-623cc91867ce.png)

This is the code that I have used to render the textured mesh in PyTorch3D:
```
lights = AmbientLights(device=device, ambient_color=((0.8,0.8,0.8),))

raster_settings = RasterizationSettings(
    image_size=4000, 
    blur_radius=0, 
    faces_per_pixel=1, 
    perspective_correct=False
)

blend_params = BlendParams(sigma=1e-4, gamma=1e-4, background_color=(0.0,0.5,0.0))

renderer_textured = MeshRenderer(
    rasterizer=MeshRasterizer(
        cameras=cur_cam, 
        raster_settings=raster_settings
    ),
    shader=SoftPhongShader(
        device=device, 
        cameras=cur_cam,
        lights=lights,
        blend_params=blend_params  
    )
)

images = renderer_textured(mesh, cameras=cur_cam, lights=lights)
```

Has anyone else experienced the same or similar problems when fitting the texture map? why is there a noticeable difference between the renderings of PyTorch3D and MeshLab/Blender?

**Comment by simon-cross** [comment]
Are there different texture sampling approaches in PyTorch3D?

**Comment by bottler** [comment]
There could be several reasons for small differences. Do you know for sure if the black lines correspond to the black background in the texture map?

**Comment by simon-cross** [comment]
I am not 100% sure but it is very likely that the black lines are from the texture map.

**Comment by JasonBoy1** [comment]
Dear @simon-cross , could you share your code of fitting texture map? I am also interested in fitting a texture map.

**Comment by JasonBoy1** [comment]
![final](https://user-images.githubusercontent.com/33180378/147540687-56a832c0-7482-4f6b-8a6b-2f6f198824d7.png)

why are your result so good? I have tried and get much worse results. Some corners cannot be seen due to the shape.
Like the belly and armpit of the cow.

**Comment by simon-cross** [comment]
In order to get better results, I used different camera positions, better evenly distributed around the model. Moreover, in order to avoid black holes in the texture map, I shifted the input images by small vertical and horizontal displacements and I updated the camera intrinsic matrices accordingly. This is necessary, since for the computation of the input images, a finite number of samples on the texture map are used, which could be insufficient to cover all the pixels of the texture map. By shifting the input images, you guarantee a theoretically infinite number of samples.

**Comment by JasonBoy1** [comment]
![final](https://user-images.githubusercontent.com/33180378/147567013-7ab6c892-0748-40ce-adf6-63ea7841d36c.png)

![image](https://user-images.githubusercontent.com/33180378/147567221-3be9e820-9c38-438c-a783-6db490b24472.png)

![image](https://user-images.githubusercontent.com/33180378/147567233-81fb21b1-b3f6-4555-9e0f-783e8d88b6a4.png)


Dear @simon-cross , thank you for your reply! This 3 images are my newly result this afternoon, about 3 hours ago.
Compared to the last result in my first comment, I add more cameras and add image smooth loss, and hinge loss to restrict the image value be in [0, 1]. These are helpful. I also use random `dist`, `elev`, `azim` to generate random R, T. But the K was determined.

But I can see that my result is still not so good as yours (could be find in the cow's tail), I think the approach you use must be very essential. 

Could you explain it with more details? Does 'shift the input images' means the rendered image to be sent into the RGB L2 loss? Since I think the texture map should not be shifted before warped onto a mesh since that will make misalignment.

If that represents the rendered images, I think your main idea is to create numerous random KRT for cameras?

**Comment by simon-cross** [comment]
By shiting the input images, I mean resampling the input image I as follows I'(x,y) = I(x+dx,y+dy), where dx and dy are small displacements. When you use the resampled image I', you need to update the principal point (x0,y0) of the intrinsic matrix as follows (x0-dx,y0-dy). In this way, you can generate more images by resampling the input images without rendering them.
