### ISSUE TITLE
Windows10 pytorch3d installation success, but the test error  

### ISSUE THREAD

**Issue by zhanghongyong123456** [facebookresearch/pytorch3d#952]
windows10 RTX 3090 cuda 11.1 pytorch1.9 python3.8 VS2019  
I followed this link and modified the setup.py file about c++14. The compilation passed, but an error occurred during testing  
https://github.com/facebookresearch/pytorch3d/issues/910#issuecomment-958759479

![image](https://user-images.githubusercontent.com/48466610/142979640-97b8923a-071e-4730-bacc-8c869d02c7fe.png)
![image](https://user-images.githubusercontent.com/48466610/142979733-38ab1475-78f2-4040-8f69-b1468a24b324.png)
I tested several.py files separately
![685fe4b25b85323e918b2e066717b91](https://user-images.githubusercontent.com/48466610/142983511-eb3fdcec-2c27-4756-8c84-038b4fec6ceb.png)
![774b8f9fefc2f4d1830dccfaa6be55d](https://user-images.githubusercontent.com/48466610/142983522-0f2daae0-3382-4255-8e69-c65b53405d34.png)
![65313d17d045fbf22b1de8a13595807](https://user-images.githubusercontent.com/48466610/142983534-7d13df40-c9f3-4e1c-a202-54cd08a8e173.png)

![cb48bf050ceba95ec7c73747d34e089](https://user-images.githubusercontent.com/48466610/142983538-0e239bc6-6157-481c-b403-fe05f7e7ad5f.png)

**Comment by bottler** [comment]
We don't run the tests on windows and there are some known problems. The io tests use temporary files in a non-windows-friendly way. The portalocker thing may be fixed by installing another package. Some small numerical differences may be expected. But the pointcloud rendering failures are more odd - it looks like that part of PyTorch3D is not working properly and I'm not sure why.
