### ISSUE TITLE
How to install Pytorch3D on Windows10？

### ISSUE THREAD

**Issue by sunshinewhy** [facebookresearch/pytorch3d#960]
## ❓ Questions on how to use PyTorch3D

I am trying to install Pytorch3D in Windows10 with CUDA 11.1, VS2019, and Pytorch 1.8.0 I tried the following commands and got the following errors.
Would you mind letting me know what I did wrong and how to correctly install it?

Thank you very much for your time and help!

The error is:
[error.txt](https://github.com/facebookresearch/pytorch3d/files/7613122/error.txt)

**Comment by bottler** [comment]
Looking at the log, you have the problem which has been seen before with `error: expected a "("`. Please see https://github.com/facebookresearch/pytorch3d/issues/876#issuecomment-943763630

**Comment by zuo12138** [comment]
I have this problem too，did you work it out?

**Comment by LewisSean** [comment]
pytorch1.8 + cuda 11.2 + win10
my first install meets the same problem with your compile log
then i **comment out Line 60** in setup.py
`# "-std=c++14",`
it worked out !
maybe this problem is due to an older compiler

**Comment by bottler** [comment]
@zuo12138 Can you look at your log file? If you see the error about `"("` then please follow #876. If not or it still isn't working, please start a new issue and include your errors/log file.

**Comment by zuo12138** [comment]
Thank you. I changed the 60 lines in the setup.py  , commented out’c + + 14’, and it worked.



---- 回复的原邮件 ----
| 发件人 | Jeremy ***@***.***> |
| 日期 | 2021年12月09日 22:19 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [facebookresearch/pytorch3d] How to install Pytorch3D on Windows10？ (Issue #960) |

@zuo12138 Can you look at your log file? If you see the error about "(" then please follow #876. If not or it still isn't working, please start a new issue and include your errors/log file.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
