### ISSUE TITLE
NVIDIA GeForce RTX 3060 Laptop GPU with CUDA capability sm_86 is not compatible 

### ISSUE THREAD

**Issue by Kiesi1991** [facebookresearch/pytorch3d#963]
Hello@All!

I have installed Pytorch3d as follows: [#959 ](https://github.com/facebookresearch/pytorch3d/issues/959)

After installing successfully pytorch3d, I am not able to use my new GPU NVIDIA GeForce RTX 3060 -> CUDA capability sm_86 is not compatible. It looks like **sm_86** is not available for Cudatoolkit=10.2

I have tried to install Cudatoolkit 11.1 and 11.3 to solve my problem, according to [#555 ](https://github.com/facebookresearch/pytorch3d/issues/555)

Unfortunately, if I use Cudatoolkit 11.3, the installation of pytorch3d is not working anymore. I am not sure which versions I have to take to get a successful environment with Pytorch3d again.

1. is Cudatoolkit 11.3 compatible with `curl -LO https://github.com/NVIDIA/cub/archive/1.10.0.tar.gz` or should I use instead `curl -LO https://github.com/NVIDIA/cub/archive/1.11.0.tar.gz`?
2. Can I use pip `install pytorch3d -f https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/py38_cu113_pyt190/download.html` to install pytorch3d?
3. if I install pytorch with `conda install -c pytorch pytorch=1.9.0 torchvision cudatoolkit=11.3`, I will get the "py3.8_cpu_0  [cpuonly]  pytorch" version [package-list_v18.txt](https://github.com/facebookresearch/pytorch3d/files/7631956/package-list_v18.txt). With this version of pytorch, I am not able to use my GPU anymore. torch.cuda.is_available()=**False**. Does anyone know, how to use my GPU with Cudatoolkit 11.3 ?

Thank you for your help!

**Comment by bottler** [comment]
Sorry this is so complicated. I'll start by just answering the numbered questions.

1. Easiest to stick with our suggested CUB version because we have seen trouble with other versions. But that trouble was with using older versions of CUDA than 11.3. I have never done much experimentation CUDA 11.3 (which ships with cub 1.11.0 I think), and so it might just work without downloading anything.

2. No this won't work. We match our wheels to the binaries provided by PyTorch, and PyTorch 1.9.0 doesn't have a CUDA 11.3 build. However, PyTorch 1.10.0 does have 11.3 builds. This is newer than our latest release, but it is supported by our nightly build, which is conda only. So if you start a new conda environment with python 3.8 cudatoolkit 11.3 PyTorch 1.10.0 and our other dependencies then `conda install -c pytorch3d-nightly pytorch3d` might work. 

3. As mentioned above, there isn't a PyTorch 1.9.0 build with cuda 11.3. Also, when installing recent PyTorch with conda you need to specify the conda-forge channel on the command line. So I think you want `conda install -c pytorch -c conda-forge pytorch=1.10.0 torchvision cudatoolkit=11.3`.

**Comment by Kiesi1991** [comment]
@bottler Thank you so much! Now it's working. The hint to use the nightly version was indeed correct. Just for clarification, I did not use the CUB 1.10. Everything is provided in pytorch 1.10.0

here is my package list from conda for all users: [package-list_pytorch3d.txt](https://github.com/facebookresearch/pytorch3d/files/7635994/package-list_pytorch3d.txt)
